-- Seed daily_insights — PERIOD phase (~80 entries)
-- Bahasa Indonesia gen-Z friendly. Mix fact/tip/support/couple/trivia/lifestyle.
-- All evidence-based atau supportive copy per CLAUDE.md tone.

insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values
-- ===== Facts (25) =====
('period', 'fact', 'Kenapa kamu bleeding?', 'Lapisan rahim (endometrium) yang dipersiapkan buat kehamilan luruh karena gak ada pembuahan. Itulah haid — proses biologis normal yang sehat.', '🩸', 1),
('period', 'fact', 'Volume darah haid', 'Rata-rata 30-80 ml per siklus. Di atas 80 ml = menorrhagia, mungkin perlu cek dokter.', '💧', 2),
('period', 'fact', 'Lama haid normal', 'ACOG bilang 2-7 hari masih normal. Kurang dari 2 atau lebih dari 7 = patut diperhatikan.', '📏', 3),
('period', 'fact', 'Kram = kontraksi rahim', 'Prostaglandin trigger rahim kontraksi buat keluarin lapisan. Lebih banyak prostaglandin = lebih sakit.', '⚡', 4),
('period', 'fact', 'Hormon lagi turun', 'Estrogen + progesteron drop saat haid. Bisa pengaruhi mood, energi, libido — itu wajar.', '📉', 5),
('period', 'fact', 'Iron loss saat haid', 'Tiap haid keluar ~15 mg iron. Itu kenapa banyak orang butuh boost iron-rich food saat ini.', '🥩', 6),
('period', 'fact', 'Endometrium tebalnya berapa?', 'Sebelum haid, lapisan rahim bisa 8-16 mm tebal. Saat haid, luruh sampai ~3 mm.', '📐', 7),
('period', 'fact', 'PMS vs PMDD', 'PMS = umum, ringan. PMDD = severe, mengganggu fungsi sehari-hari. Kalau PMS-mu sangat berat, bisa konsultasi.', '💭', 8),
('period', 'fact', 'Warna haid bisa berubah', 'Merah cerah = darah segar, gelap = lebih lama di rahim. Coklat di awal/akhir normal.', '🎨', 9),
('period', 'fact', 'Sumber kram', 'Selain prostaglandin, kondisi seperti endometriosis atau fibroid juga bisa bikin kram parah.', '🔬', 10),
('period', 'fact', 'Cycle = 1 dari 5 vital signs', 'American Academy of Pediatrics resmiin haid sebagai vital sign — sama pentingnya kayak detak jantung untuk kesehatan.', '❤️', 11),
('period', 'fact', 'Anemia warning', 'Kalau lemes parah, pucat, jantung berdebar saat haid — bisa jadi anemia. Cek hemoglobin kalau berulang.', '⚠️', 12),
('period', 'fact', 'Kapan ovulasi terjadi?', 'Sekitar 14 hari sebelum haid berikutnya. Bukan 14 hari setelah haid mulai (kecuali siklusmu pas 28 hari).', '🥚', 13),
('period', 'fact', 'Bekuan darah normal?', 'Bekuan kecil (<2 cm) saat haid berat normal. Kalau besar/banyak/sering, konsul dokter.', '🩺', 14),
('period', 'fact', 'Stress impact haid', 'Stress bisa delay ovulasi → siklus jadi lebih panjang. Bukan haidnya yang ke-trigger stress, tapi siklus full-nya.', '😰', 15),
('period', 'fact', 'Sleep + period', 'Saat haid, body temperature turun. Bisa tidur lebih nyenyak, atau malah susah karena cramps. Pakai layered blanket.', '🌙', 16),
('period', 'fact', 'Headache saat haid?', 'Estrogen drop bisa trigger menstrual migraine. Coba magnesium 400mg + hidrasi.', '🤕', 17),
('period', 'fact', 'Mood swing root cause', 'Drop hormonal di akhir luteal + awal haid pengaruhi serotonin di otak. Bukan "kamu lebay" — itu biokimia.', '🧠', 18),
('period', 'fact', 'Iron + vitamin C combo', 'Vitamin C bantu absorpsi iron 3-6x lipat. Makan jeruk + bayam = duo power saat haid.', '🍊', 19),
('period', 'fact', 'Caffeine + cramps', 'Caffeine bisa konstrik pembuluh darah → kram lebih sakit. Coba kurangi 1-2 hari awal haid.', '☕', 20),
('period', 'fact', 'Olahraga ringan = relief', 'Endorphins natural painkiller. Yoga atau jalan kaki 20 menit bisa kurangin kram up to 25%.', '🧘‍♀️', 21),
('period', 'fact', 'Period sync myth', 'Studi besar (Oxford 2017) bilang teman tinggal serumah sync siklus = mostly chance, bukan biological synchronization.', '👯', 22),
('period', 'fact', 'Heat helps how?', 'Suhu hangat (40°C) di perut bawah bisa kurangin kram seefektif ibuprofen, per studi 2012.', '🔥', 23),
('period', 'fact', 'Pads vs cup vs tampon', 'Cup = 8-12 jam, hemat & eco. Tampon = aktif, max 8 jam (TSS risk). Pads = paling simpel. Pilih sesuai comfort.', '🎒', 24),
('period', 'fact', 'Period in animals', 'Cuma ~85 mamalia yang haid (manusia, primata, kelelawar, gajah). Sisanya reabsorpsi endometrium tanpa bleeding.', '🐘', 25),

-- ===== Tips (20) =====
('period', 'tip', 'Kompres hangat = lifesaver', 'Botol air panas atau heating pad di perut bawah, 15-20 menit. Sederhana tapi works.', '🧴', 30),
('period', 'tip', 'Magnesium buat cramps', 'Magnesium glycinate 200-400mg bisa kurangin kram. Bisa juga dari almond, dark chocolate, bayam.', '🍫', 31),
('period', 'tip', 'Hidrasi dobel', 'Air putih 2.5L per hari saat haid. Bisa kurangin bloating + bantu flush retensi cairan.', '💧', 32),
('period', 'tip', 'Bantal di antara lutut', 'Tidur miring dengan bantal di antara lutut = posisi paling nyaman buat banyak orang saat haid.', '🛏️', 33),
('period', 'tip', 'Yoga child pose', 'Child pose, cat-cow, supine twist. Pose lembut buat kurangin tension di pelvis. Hindari inversi (pose terbalik).', '🤸‍♀️', 34),
('period', 'tip', 'Dark chocolate ≥70%', 'Magnesium + antioksidan + endorphin trigger. Plus enak. Win-win comfort food.', '🍫', 35),
('period', 'tip', 'Avoid super salty foods', 'Sodium tinggi = retensi air = bloat lebih parah. Skip ramen instan + chips di hari haid.', '🚫', 36),
('period', 'tip', 'Gentle exercise > rest only', 'Jalan kaki 20 menit > diem aja. Pelan tapi gerakin tubuh, gak harus full workout.', '🚶‍♀️', 37),
('period', 'tip', 'Ibuprofen prophylactic', 'Mulai ibuprofen 1-2 hari SEBELUM haid, dosis sesuai anjuran. Lebih efektif dari "tunggu sakit dulu".', '💊', 38),
('period', 'tip', 'Underwear cantik', 'Period underwear absorbent (Modibodi, Thinx) bisa replace pads buat hari ringan. Lebih aman + comfy.', '👙', 39),
('period', 'tip', 'Tea: chamomile + ginger', 'Chamomile relax otot, ginger anti-inflammatory. Combo teh hangat sebelum tidur = bliss.', '🍵', 40),
('period', 'tip', 'Iron-rich plate', 'Hati ayam, daging merah, bayam, lentil, tahu. Pasangin sama buah vit C buat absorpsi maksimal.', '🍽️', 41),
('period', 'tip', 'Skin care simpler', 'Hormonal jerawat di hari haid umum. Stick ke basic routine, jangan overcorrect dengan exfoliant agresif.', '🧴', 42),
('period', 'tip', 'Sleep priority', 'Tidur 8-9 jam saat haid. Body lagi extra healing, butuh recovery time.', '😴', 43),
('period', 'tip', 'Reduce screen evening', 'Blue light + melatonin disruption + period mood = recipe susah tidur. Off devices 1 jam sebelum tidur.', '📵', 44),
('period', 'tip', 'Soft fabrics only', 'Skip celana ketat + elastic agresif di pinggang. Loose pants, kaftan, dress = friend di hari haid.', '👗', 45),
('period', 'tip', 'Sup hangat protein', 'Sup ayam, soto, atau bone broth. Hidrasi + protein + comfort. Nutrient absorbsi lebih mudah saat liquid.', '🍲', 46),
('period', 'tip', 'TENS unit (jangka panjang)', 'TENS machine kecil di bawah Rp 300rb, taro di perut bawah, electrical stimulation = pain relief. Banyak pakai jangka panjang.', '⚡', 47),
('period', 'tip', 'Heating in waist', 'Selain perut, kompres di lower back juga work — banyak nyeri haid radiate ke punggung.', '🌡️', 48),
('period', 'tip', 'Schedule lighter today', 'Gak harus skip kerjaan, tapi rearrange task — mental-heavy jadi stuff yang flow easier. Heavy meeting → besok.', '📅', 49),

-- ===== Support (15) =====
('period', 'support', 'Hari ini boleh slow', 'Tubuhmu lagi kerja keras secara internal. Slow down bukan kemalasan, itu honoring diri sendiri.', '💚', 60),
('period', 'support', 'Mood drop bukan salahmu', 'Hormonal shift real. Kalau hari ini ngerasa down, bukan karena lo lemah — itu biologi.', '🤗', 61),
('period', 'support', 'Self-talk yang lembut', 'Coba ngomong ke diri kayak ngomong ke teman dekat yang lagi sakit. Lembut, supportive, no judgment.', '💌', 62),
('period', 'support', 'Cry kalau perlu', 'Nangis bisa release oksitosin + endorphin. Kalau body minta, kasih ruang. Healthy outlet.', '😭', 63),
('period', 'support', 'Comfort > productivity', 'Hari ini boleh prioritize comfort daripada checklist task. Worth lo bukan dari output hari ini.', '☕', 64),
('period', 'support', 'Body wisdom', 'Tubuhmu kasih tau apa yang dia butuh. Listen — kalau pegal minta rebahan, kasih. Kalau lapar minta makan, kasih.', '🫶', 65),
('period', 'support', 'You''re doing great', 'Show up walau lagi gak enak = strong move. Lo udah cukup ngelakuin yang lo bisa hari ini.', '🌸', 66),
('period', 'support', 'Saying no is OK', '"Maaf, hari ini gw butuh rest" = full sentence. Gak perlu over-explain alasan.', '🛑', 67),
('period', 'support', 'Imperfect is fine', 'Hari ini gak pakai makeup, gak rapi, gak super-productive — itu OK. Real life happens.', '✨', 68),
('period', 'support', 'Pain is signal, not punishment', 'Sakit yang lo rasa = body lagi ngomong. Bukan lo dihukum karena sesuatu. Dengerin.', '🌷', 69),
('period', 'support', 'Permission slip: rest', 'Dengan ini, lo dikasih izin buat rest hari ini. Dari diri sendiri, untuk diri sendiri.', '🎫', 70),
('period', 'support', 'Hubungin orang dipercaya', 'Kadang bercerita ke orang yang lo percaya = relief tersendiri. Gak perlu solusi, cuma didengar.', '📞', 71),
('period', 'support', 'Bukan moody, lagi shifting', 'Mood-mu hari ini valid. Bukan "moody" — lo lagi navigate hormonal shift, itu nyata.', '🌊', 72),
('period', 'support', 'Honor cycle, honor self', 'Period bukan inconvenience. Itu bagian dari rhythm tubuhmu. Honoring it = honoring yourself.', '🌙', 73),
('period', 'support', 'Perfect day gak ada', 'Tiap hari beda level kapasitas. Yang penting tetap maju, gak harus selalu di puncak.', '⛰️', 74),

-- ===== Couple (10) =====
('period', 'couple', 'Pasangan bisa ngapain?', 'Tawarin heating pad, snack favorit, atau pelukan. Gak perlu fix — kadang yang dibutuhkan cuma ditemenin.', '🤝', 80),
('period', 'couple', 'Nggak suka disentuh? OK', 'Beberapa orang sentuhan saat kram bikin tambah sakit. Sampein ke pasangan tanpa rasa bersalah.', '🚧', 81),
('period', 'couple', 'Buat sup buat pasangan', 'Sup ayam hangat, oatmeal, atau buah seger = comfort food. Kasih jadi quality time tanpa kata-kata.', '🍜', 82),
('period', 'couple', 'Massage pinggang lower', 'Pijat lembut di lower back / pinggang bisa relief radiating period pain. Tanya dulu, jangan langsung.', '💆‍♀️', 83),
('period', 'couple', 'Distraction therapy', 'Movie marathon, board game, atau cerita lucu — kadang distraction = obat paling underrated.', '🎬', 84),
('period', 'couple', 'Belajar siklusnya', 'Tracking kapan haid pasangan biasanya datang = bisa antisipasi support. Bukan privacy invasion, justru caring.', '📅', 85),
('period', 'couple', 'Komunikasi over assumption', 'Tanya "ada yang gw bisa bantu?" daripada nebak. Tiap orang beda kebutuhannya.', '💬', 86),
('period', 'couple', 'Hindari "Lagi PMS ya?"', 'Ini dismissive walau niat bercanda. Mood valid tanpa harus dikaitkan ke siklus tiap saat.', '🚫', 87),
('period', 'couple', 'Bawa essentials saat keluar', 'Tas pasangan bisa stash extra pad/tampon/painkiller. Be the partner that''s prepared.', '🎒', 88),
('period', 'couple', 'Affirmation simple', '"Kamu kuat banget tahan sakit gini." "Hari ini gpp slow, gw ada." Kata-kata lembut go a long way.', '💕', 89),

-- ===== Trivia (5) =====
('period', 'trivia', 'Tampon = ancient invention', 'Mesir kuno pakai softened papyrus, Romawi pakai wool, Greek pakai linen. Tampon modern (1933) = inovasi belum lama.', '📜', 95),
('period', 'trivia', 'Period leave di Asia', 'Jepang punya menstrual leave sejak 1947. Korea, Indonesia, Taiwan juga punya provisi serupa di UU ketenagakerjaan.', '🌏', 96),
('period', 'trivia', 'Pink tax di pads', '"Pink tax" — pads + tampon dikenakan PPN di banyak negara. India hapus 2018, Skotlandia provide gratis 2020.', '💸', 97),
('period', 'trivia', 'First period record', 'Perempuan rata-rata mengalami menarche (haid pertama) di umur 12-13 thn. Trend turun dari 16 thn (1860) ke 12 thn (kini).', '🎂', 98),
('period', 'trivia', 'Monthly = lunar?', 'Kata "menstruation" dari Latin "mensis" (bulan). Banyak budaya kuno linkin siklus ke moon — sains bilang gak ada korelasi reliable, tapi etymology stays.', '🌕', 99),

-- ===== Lifestyle (5) =====
('period', 'lifestyle', 'Workout adjusted', 'Kalau biasanya HIIT, switch ke yoga / pilates ringan. Body lagi healing, bukan time push limit.', '🧘', 105),
('period', 'lifestyle', 'Skin: mengurangi makeup', 'Pori lebih open saat haid, makeup lebih clog. Coba minimal makeup days, biarin skin breathe.', '🌿', 106),
('period', 'lifestyle', 'Plan perfect rest day', 'Sarung, teh hangat, buku ringan, podcast favorit. Bikin rest day yang lo nantikan.', '☁️', 107),
('period', 'lifestyle', 'Music for mood', 'Bikin playlist khusus haid — lagu yang lembut, slow, atau yang biasa lo dengerin saat butuh comfort.', '🎵', 108),
('period', 'lifestyle', 'Aromatherapy lavender', 'Essential oil lavender, peppermint, atau clary sage di diffuser bisa kurangin tension. Lavender favorit untuk relax.', '🪷', 109);
