-- Seed daily_insights — FOLLICULAR phase (~75 entries)

insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values
-- ===== Facts (22) =====
('follicular', 'fact', 'Welcome to follicular!', 'Setelah haid selesai, follicle di ovarium mulai matang. Estrogen naik perlahan = energi kembali.', '🌱', 1),
('follicular', 'fact', 'Estrogen rising', 'Estrogen meningkat 5-7 hari setelah haid mulai. Mood + energy biasanya naik linear.', '📈', 2),
('follicular', 'fact', 'Best phase for new things', 'Cognitive function + verbal fluency lebih bagus di follicular per studi 2014. Time buat tackle project baru.', '🎯', 3),
('follicular', 'fact', 'Skin glow time', 'Estrogen rising = produksi kolagen up. Skin biasanya looking lebih plump + glowy.', '✨', 4),
('follicular', 'fact', 'Lupa nyeri haid', 'Endorphin reset post-haid + hormonal shift = banyak yang feel "almost forgot what cramps felt like".', '🌈', 5),
('follicular', 'fact', 'Workout capacity tinggi', 'Strength + endurance bisa peak di akhir follicular. Body recover dari haid + estrogen anabolic effect.', '💪', 6),
('follicular', 'fact', 'LH masih low', 'Luteinizing hormone (LH) baru spike dekat ovulasi. Selama follicular, LH stabil rendah.', '📊', 7),
('follicular', 'fact', 'FSH = star pemeran', 'Follicle-stimulating hormone (FSH) yang trigger telur matang di ovarium. Naik di awal follicular.', '⭐', 8),
('follicular', 'fact', 'Cervical mucus changes', 'Awal follicular = sticky/dry. Late follicular = creamy → wet (preview fertile window incoming).', '💧', 9),
('follicular', 'fact', 'BBT base level', 'Basal Body Temperature = 36.1-36.4°C selama follicular (low phase). Naik di ovulasi.', '🌡️', 10),
('follicular', 'fact', 'Fertility window approaching', 'Fertile window mulai ~5 hari sebelum ovulasi. Late follicular = window starting.', '🪟', 11),
('follicular', 'fact', 'Cognitive boost', 'Penelitian fMRI: hippocampus + prefrontal cortex aktivitas meningkat saat estrogen tinggi.', '🧠', 12),
('follicular', 'fact', 'Mood baseline up', 'Serotonin lebih tersedia saat estrogen tinggi. Default mood biasanya lebih cerah.', '☀️', 13),
('follicular', 'fact', 'Insulin sensitivity', 'Body lebih sensitive ke insulin di follicular = carbs di-utilized lebih efisien.', '🍚', 14),
('follicular', 'fact', 'Hair growth period', 'Estrogen prolong growth phase rambut. Hair feels thicker + lebih lush minggu ini.', '💁‍♀️', 15),
('follicular', 'fact', 'Voice subtle changes', 'Studi 2008: voice pitch sedikit naik saat estrogen tinggi. Subtle, tapi konsisten.', '🎤', 16),
('follicular', 'fact', 'Late follicular = late teens energy', 'Banyak orang describe energi late follicular kayak "balik ke umur 18". It''s the estrogen.', '🚀', 17),
('follicular', 'fact', 'Stress tolerance higher', 'Cortisol response lebih baik kontrol di follicular vs luteal. Stressful task — handle now.', '🛡️', 18),
('follicular', 'fact', 'Sleep deeper', 'BBT lebih rendah = sleep biasanya lebih restorative. Quality > quantity di phase ini.', '😴', 19),
('follicular', 'fact', 'Pain threshold up', 'Estrogen modulate persepsi pain. Same pain feel less intense vs luteal phase.', '🦾', 20),
('follicular', 'fact', 'Verbal memory peaks', 'Recall + word retrieval better saat estrogen tinggi (Hampson 1990). Pidato? Ujian lisan? Now.', '📚', 21),
('follicular', 'fact', 'Estrogen + dopamine', 'Estrogen naikkan dopamine signaling = motivasi + reward feeling lebih strong.', '🎉', 22),

-- ===== Tips (20) =====
('follicular', 'tip', 'Mulai project baru', 'Mood up + energy up + cognitive sharp. Start project yang udah mandek atau learning baru.', '🚀', 30),
('follicular', 'tip', 'Strength training', 'Phase paling cocok lift heavier. Body build muscle lebih efisien dengan support estrogen.', '🏋️‍♀️', 31),
('follicular', 'tip', 'Schedule big meetings', 'Verbal fluency peak. Presentation, negotiation, social events — schedule di follicular kalau bisa.', '🗣️', 32),
('follicular', 'tip', 'Try new recipes', 'Adventurous palate phase — kalau biasanya picky, sekarang coba yang baru. Reward circuits responsive.', '🍳', 33),
('follicular', 'tip', 'Meal prep ahead', 'Energy + clarity = good time prep food untuk minggu depan saat luteal/period bakal lebih lelah.', '🥗', 34),
('follicular', 'tip', 'Social calendar', 'Plan hangout, dinner, networking. Follicular = peak social bandwidth.', '🎈', 35),
('follicular', 'tip', 'Belajar skill baru', 'Brain in absorbent mode. Course online, language app, coding tutorial — momentum favorable.', '🎓', 36),
('follicular', 'tip', 'Cardio peak performance', 'VO2 max sedikit lebih tinggi. Run, HIIT, atau cycling = personal record territory.', '🏃‍♀️', 37),
('follicular', 'tip', 'Beauty + skincare lab', 'Skin lebih responsive ke active ingredients. Time intro retinol/AHA gradually (kalau belum).', '💄', 38),
('follicular', 'tip', 'Declutter weekend', 'Energy + decisiveness up. Time bersih-bersih, donate stuff, organize closet.', '🧹', 39),
('follicular', 'tip', 'Brunch with friends', 'Mood naturally good. Schedule quality time dengan orang yang kamu sayang.', '🥞', 40),
('follicular', 'tip', 'Negotiate raise', 'Confidence + verbal articulation peak. Ask for promotion atau raise di phase ini kalau bisa pilih.', '💰', 41),
('follicular', 'tip', 'Date night plan', 'Libido starting to climb. Romantic plans, flirty outfits, date night ideas — semua align.', '💕', 42),
('follicular', 'tip', 'Eat protein-rich', 'Muscle synthesis higher. Pastikan protein cukup (1.6-2g/kg) buat capitalize on follicular gain potential.', '🥩', 43),
('follicular', 'tip', 'Hydrate consistently', 'Active phase = more water turnover. Aim 2.5-3L/day.', '💦', 44),
('follicular', 'tip', 'Cold exposure', 'Cold shower atau ice bath toleransi lebih tinggi. Boost dopamine + immune response.', '🧊', 45),
('follicular', 'tip', 'Big ideas brainstorm', 'Take walk + pen & paper. Creativity flow = ideas just come. Capture them sebelum lupa.', '📝', 46),
('follicular', 'tip', 'Sleep stay consistent', '7-9 jam tetap penting walau energy feel high. Don''t skip sleep just because lagi capable.', '🛌', 47),
('follicular', 'tip', 'Ask hard questions', 'Hard conversations, feedback meetings, tricky negotiations — emotionally regulated phase = good fit.', '💬', 48),
('follicular', 'tip', 'Practice mindfulness pre-luteal', 'Meditation muscle dibangun di follicular = bekal saat luteal moods tougher. Investment.', '🧘', 49),

-- ===== Support (12) =====
('follicular', 'support', 'Capitalize while you can', 'Phase ini naturally easier. Tapi gak harus push 100% — sustainable energy > burnout cycle.', '⚡', 60),
('follicular', 'support', 'Selamat datang back', 'Setelah period yang berat, body lo udah balik. Kasih appreciation buat yourself yang udah survive.', '🌷', 61),
('follicular', 'support', 'Energy ≠ obligation', 'Punya energy bukan berarti must produce. Boleh juga channel ke hobi yang gak "produktif" — itu valid.', '🎨', 62),
('follicular', 'support', 'You contain multitudes', 'Lo di follicular beda dari lo di luteal — keduanya valid versi diri lo. Embrace both.', '🌗', 63),
('follicular', 'support', 'Progress count', 'Hari ini berasa easier — gunakan untuk hal yang biasanya hard. Setiap step adds up.', '📈', 64),
('follicular', 'support', 'Body is wise', 'Body knows kapan butuh rest, kapan butuh push. Listen — kalau follicular minta active, follow.', '🌿', 65),
('follicular', 'support', 'Joy is medicine', 'Follicular often feel optimistic. Soak it in — joy itself is valid output, gak cuma productivity.', '☀️', 66),
('follicular', 'support', 'Make momentum', 'Action while motivated > waiting for motivation. Follicular = window action.', '🌊', 67),
('follicular', 'support', 'Compassionate to past you', 'Yang lo achieve hari ini, ada thanks ke past-you yang grit through period. Honor them.', '🙏', 68),
('follicular', 'support', 'Move at your pace', 'Society push hustle 24/7. Follow your hormonal rhythm — itu actually more efficient.', '🦋', 69),
('follicular', 'support', 'Curiosity as compass', 'Follicular lights up curiosity. What''s calling you? Follow that pull.', '🧭', 70),
('follicular', 'support', 'Saying yes feels natural', 'Boundaries still matter, but easier to lean into opportunity now. Say yes selectively, mindfully.', '✅', 71),

-- ===== Couple (8) =====
('follicular', 'couple', 'Plan adventure together', 'Pasangan di follicular = adventure-mode aktif. Hiking, cafe-hop baru, museum visit. Channel energy.', '🗺️', 80),
('follicular', 'couple', 'Heart-to-heart talk', 'Late follicular emotions stable + clarity tinggi. Time bahas long-term plans, finances, goals.', '💬', 81),
('follicular', 'couple', 'Cook together', 'Energy buat experiment recipe ada. Cook together as quality time + skill share.', '👩‍🍳', 82),
('follicular', 'couple', 'Notice the energy shift', 'Pasangan supporter bisa notice "lo lebih cheerful minggu ini" — naming it = validation.', '👀', 83),
('follicular', 'couple', 'Date night active', 'Bowling, mini golf, salsa kelas. Active date > sit-down dinner saat energy up.', '🎳', 84),
('follicular', 'couple', 'Conflict resolve now', 'Kalau ada unresolved disagreement dari minggu lalu, bahas sekarang. Both more regulated.', '🕊️', 85),
('follicular', 'couple', 'Photo memory', 'Phase rasa kayak vibrant — capture momen. Photo bareng yang random tapi meaningful.', '📸', 86),
('follicular', 'couple', 'Plan the surprise', 'Lo di follicular = ide kreatif flowing. Plan surprise birthday, anniversary, atau just-because gift.', '🎁', 87),

-- ===== Trivia + Lifestyle (13) =====
('follicular', 'trivia', '"Follicle" etymology', 'Dari Latin "folliculus" = small bag. Follicle ovarium = kantong kecil tempat egg matang.', '📖', 95),
('follicular', 'trivia', '15-20 follicles per cycle', 'Tiap cycle, 15-20 follicle mulai matang. Tapi cuma 1 (rarely 2) yang dominant + ovulate.', '🎲', 96),
('follicular', 'trivia', 'Atresia process', 'Follicle non-dominant degenerate via atresia. Body select 1 yang fittest — biological natural selection.', '🔬', 97),
('follicular', 'trivia', 'Egg pool depleting', 'Birth: 1-2 juta eggs. Puberty: 300-400k. Tiap cycle 1000+ depleted via atresia. Why menopause natural.', '📉', 98),
('follicular', 'trivia', 'Estrogen 3 forms', 'Estradiol (E2) — main reproductive years. Estriol (E3) — pregnancy. Estrone (E1) — post-menopause.', '🧪', 99),

('follicular', 'lifestyle', 'Outfit lebih bold', 'Mood adventurous = coba outfit yang biasa hesitate pakai. Color, pattern, statement piece.', '👗', 105),
('follicular', 'lifestyle', 'Skincare routine A-game', 'Time consistent dengan routine. Hasil akan compound.', '🧴', 106),
('follicular', 'lifestyle', 'Music: upbeat playlist', 'Pop, dance, fun. Pas sama mood naturally cheerful.', '🎶', 107),
('follicular', 'lifestyle', 'Outdoor over indoor', 'Sun + fresh air amplify estrogen mood boost. Walk, picnic, atau ngerjain di taman.', '🌳', 108),
('follicular', 'lifestyle', 'Try standing desk', 'Energy buat handle posisi alternated. Save back, save calories, productive.', '🪑', 109),
('follicular', 'lifestyle', 'Schedule yearly checkups', 'Energy + organisation. Kalau ada appointment dokter, dentist, mata yang ditunda — book sekarang.', '🩺', 110),
('follicular', 'lifestyle', 'Reading challenge', 'Cognitive sharp + curious. Mulai buku panjang yang biasanya intimidating.', '📚', 111),
('follicular', 'lifestyle', 'Garden time', 'Kalau punya plant, time repot, prune, fertilize. Care + nature time = double therapeutic.', '🪴', 112);
