-- Seed daily_insights — FERTILE WINDOW phase (~75 entries)
-- Note: 'fertile' phase di app = pre-ovulation 5 days. Ovulation day = 'ovulation'.

insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values
-- ===== Facts (24) =====
('fertile', 'fact', 'Welcome fertile window', 'Sperma bisa survive 5 hari di tubuh. Ditambah egg viable 24h saat ovulasi = 6-day window konsepsi.', '🪟', 1),
('fertile', 'fact', 'Cervical mucus = key sign', 'Mucus jadi kayak putih telur (egg-white): bening, stretchy, slippery. Sign body siap konsepsi.', '🥚', 2),
('fertile', 'fact', 'Cervix position changes', 'Cervix naik lebih tinggi, jadi softer + lebih open. Kalau lo cek manual, beda jelas dari hari biasa.', '🔝', 3),
('fertile', 'fact', 'BBT belum naik', 'Basal body temperature masih low di fertile window pre-ovulasi. Naik baru SETELAH ovulasi.', '🌡️', 4),
('fertile', 'fact', 'LH starting to rise', 'Luteinizing hormone mulai naik 24-36 jam sebelum ovulasi. LH test strip jadi positif.', '📈', 5),
('fertile', 'fact', 'Estrogen peak', 'Estrogen reach peak ~1 hari sebelum ovulasi. Inilah yang trigger LH surge.', '⛰️', 6),
('fertile', 'fact', 'Libido natural rise', 'Hormonal cocktail di fertile = libido naik biological. Bukan accidental — body ngajak reproductive activity.', '💕', 7),
('fertile', 'fact', 'Ovulation pain (mittelschmerz)', '15-20% orang feel sakit ringan di sisi ovarium yang ovulate. Sharp twinge atau dull ache, beberapa jam.', '⚡', 8),
('fertile', 'fact', 'Skin glow peak', 'Estrogen + progesteron balance + circulation up = banyak orang look "best skin" di fertile window.', '✨', 9),
('fertile', 'fact', 'Conception probability', 'Hari -2 sebelum ovulasi = 33% chance konsepsi (puncak). Hari ovulasi = 27%. Drop drastis after.', '📊', 10),
('fertile', 'fact', 'Sperm survival 5 days', 'Sperma di cervical mucus fertile bisa survive 5 hari. Itu kenapa fertile window mulai 5 hari sebelum ovulasi.', '🏊', 11),
('fertile', 'fact', 'Egg = single shot', 'Egg viable cuma 12-24 jam after release. Sperma bisa nunggu, egg gak bisa.', '⏰', 12),
('fertile', 'fact', 'Voice subtle higher', 'Studi 2008 (Bryant): perempuan suara sedikit lebih tinggi di fertile window. Subliminal signal.', '🎤', 13),
('fertile', 'fact', 'Smell more sensitive', 'Estrogen amplify smell perception. Banyak laporan "everything smells stronger" di fertile.', '👃', 14),
('fertile', 'fact', 'Attractiveness studies', 'Studi multiple (Roberts 2004, Haselton 2007): perempuan rated more attractive di fertile by laki-laki blind to cycle phase.', '🌹', 15),
('fertile', 'fact', 'Risk-taking down', 'Counterintuitive — risk-taking sebenarnya turun di fertile (Bröder 2003). Caution mode subconscious.', '🛡️', 16),
('fertile', 'fact', 'Body awareness peaks', 'Kinesthetic awareness lebih tinggi. Banyak yang feel "in tune with body" specifically saat fertile.', '🧘‍♀️', 17),
('fertile', 'fact', 'Saliva ferning', 'Saliva di-dry on glass + microscope = pattern ferning saat estrogen tinggi. Fertility tracker hack.', '🔬', 18),
('fertile', 'fact', 'Sleep deeper', 'Pre-ovulation BBT low + serotonin balanced = deep sleep more accessible.', '🌙', 19),
('fertile', 'fact', 'Cervix soft like lips', 'Pre-fertile: firm kayak hidung. Fertile: soft kayak bibir. Tactile sign signifikan.', '👄', 20),
('fertile', 'fact', 'Spinnbarkeit test', 'Tarik mucus antara 2 jari. Stretchy 5-10 cm tanpa putus = peak fertility. Sebutan resmi: spinnbarkeit.', '📏', 21),
('fertile', 'fact', 'Conception beyond fertile', 'Walaupun fertile window 6 hari, konsepsi paling probable di hari -1 + 0 (ovulation day). Sperm + egg both fresh.', '🎯', 22),
('fertile', 'fact', 'Energy still high', 'Estrogen tinggi = energy carry-over dari follicular. Workouts + projects masih flowing.', '⚡', 23),
('fertile', 'fact', 'Why "fertile" matters tracking', 'Even kalau gak planning konsepsi, knowing window = empowerment. Body literacy = self-care foundation.', '📚', 24),

-- ===== Tips (20) =====
('fertile', 'tip', 'Cek mucus pas mandi', 'Bilas dengan tissue pas pup, atau jari saat shower. Wet, slippery, stretchy = peak.', '🚿', 30),
('fertile', 'tip', 'BBT measurement consistency', 'Ukur saat bangun tidur SEBELUM gerak, jam yang sama. Pre-ovulasi steady, post jelas naik.', '🌡️', 31),
('fertile', 'tip', 'LH strip morning + sore', 'LH surge 24-36 jam. Tes 2x sehari tangkap timing optimal kalau planning konsepsi.', '🧪', 32),
('fertile', 'tip', 'Folate kalau planning konsepsi', '400 mcg folate harian, mulai 3 bulan sebelum konsepsi. Reduce neural tube defect risk dramatically.', '🥬', 33),
('fertile', 'tip', 'Avoid alkohol kalau trying', 'Alkohol pengaruhi sperm quality (kalau partner male) + egg quality. Cut atau minimize at fertile.', '🚫', 34),
('fertile', 'tip', 'Hydration extra', 'Cervical mucus quality tergantung hidrasi. Air putih cukup = mucus sehat, sperm-friendly.', '💧', 35),
('fertile', 'tip', 'Lubricant aware', 'Most lube spermicidal. Kalau trying konsepsi, pakai sperm-friendly (Pre-Seed) atau alami.', '🧴', 36),
('fertile', 'tip', 'Avoid hot tubs (male partner)', 'Sperma ideal 1-2°C below body temp. Hot tub berkala kurangi sperm quality (recover dalam 3 bulan).', '🚿', 37),
('fertile', 'tip', 'Reduce caffeine', 'Caffeine berlebih (>300mg/day) terkait konsepsi delay. Kurangi kalau planning.', '☕', 38),
('fertile', 'tip', 'Body type changes', 'Subtle: perut sedikit kembung, breast tender ringan. Body kasih signal — pay attention.', '👀', 39),
('fertile', 'tip', 'Ovulation predictor kit', 'OPK detect LH surge. Pee on stick, baca dalam 5 menit. 95% accurate kalau pas kalibrasi.', '📍', 40),
('fertile', 'tip', 'Maintain healthy weight', 'BMI ekstrem (under/over) bisa disrupt ovulasi. Healthy range = regular cycles + better fertility.', '⚖️', 41),
('fertile', 'tip', 'Quit smoking', 'Smoking accelerate ovarian aging. Tiap pack-year = AMH (egg reserve) marker turun.', '🚭', 42),
('fertile', 'tip', 'Sleep 7-9 jam', 'Sleep deprivation disrupt LH surge timing. Konsepsi harder kalau chronic sleep loss.', '😴', 43),
('fertile', 'tip', 'Stress management', 'Cortisol tinggi delay ovulasi. Yoga, meditation, walk in nature — anything yang lo find calming.', '🧘', 44),
('fertile', 'tip', 'Sexual frequency', 'Konsepsi: every 1-2 days di fertile window optimal. Daily OK juga, sperm count recover cepat.', '🛏️', 45),
('fertile', 'tip', 'Position myth', 'No scientific evidence position pengaruhi konsepsi probability. Whatever feels good.', '💫', 46),
('fertile', 'tip', 'Post-coital rest', 'Lying flat 10-15 menit post-sex bisa bantu sperm reach cervix. Anecdotal tapi harmless.', '🛌', 47),
('fertile', 'tip', 'Mood awareness', 'Some experience hyper-aware, others slightly anxious due to body changes. Both normal.', '🤔', 48),
('fertile', 'tip', 'Track patterns over months', 'Tiap fertile window beda subtly. Tracking 3+ months = personal pattern muncul.', '📈', 49),

-- ===== Support (10) =====
('fertile', 'support', 'Body knows what to do', 'Whether trying konsepsi atau gak, fertile window = window body kerja paling busy. Trust the system.', '🪴', 60),
('fertile', 'support', 'Fertility ≠ obligation', 'Punya fertile window doesn''t mean must pursue konsepsi. Window untuk awareness, bukan pressure.', '🕊️', 61),
('fertile', 'support', 'Awareness is power', 'Knowing kapan body ovulate = knowing self. Bisa decide, plan, atau just observe — empowered.', '💪', 62),
('fertile', 'support', 'Cycle is data', 'Tiap signal hari ini = data. Lo lagi belajar bahasa body sendiri. Skill seumur hidup.', '🔤', 63),
('fertile', 'support', 'Honor the rhythm', 'Modern life often demands constant output. Cycle remind: rhythm is biological, not weakness.', '🌊', 64),
('fertile', 'support', 'Sensual but optional', 'Rasa "alive" lebih intense saat fertile. Channel kemana lo mau — art, dance, intimacy, hobby.', '🌹', 65),
('fertile', 'support', 'Fertility not equal womanhood', 'Lo tetap whole + valid regardless fertility status. This is one signal, bukan defining identity.', '🌟', 66),
('fertile', 'support', 'Hope amid trying', 'Kalau trying konsepsi: tiap cycle = hope. Even kalau cycle ini gak result, ke-hope tetep alive.', '🌅', 67),
('fertile', 'support', 'Patience with body', 'Konsepsi rata-rata butuh 6-12 cycles untuk healthy couples. Patience > panic.', '⏳', 68),
('fertile', 'support', 'No moral hierarchy', 'Konsepsi vs gak konsepsi = pilihan personal, bukan moral test. Self-trust yang penting.', '⚖️', 69),

-- ===== Couple (10) =====
('fertile', 'couple', 'Communication open', 'Whether trying or avoiding pregnancy, fertile = phase keterbukaan. Talk priority + plan.', '🗨️', 80),
('fertile', 'couple', 'Quality > quantity sex', 'Trying konsepsi: gak harus daily. Every 1-2 day enough + lebih sustainable energi.', '✨', 81),
('fertile', 'couple', 'Romantic gestures', 'Even no plan konsepsi, romantic gesture = nice di phase ini. Date, flowers, surprise.', '🌷', 82),
('fertile', 'couple', 'Pasangan supporter aware', 'Notice mood + energy uptick di pasangan. Supportive presence > intervention.', '👁️', 83),
('fertile', 'couple', 'Mutual decision konsepsi', 'Kalau pertimbangkan konsepsi, percakapan ini hari-hari. Both sides aligned = healthier path.', '🤝', 84),
('fertile', 'couple', 'Birth control reliable', 'Kalau menghindari konsepsi, fertile window = paling vigilant. Backup method (kondom + tracking).', '🛡️', 85),
('fertile', 'couple', 'Touch quality high', 'Estrogen amplify pleasant touch perception. Cuddle session > screen scrolling tonight.', '🤗', 86),
('fertile', 'couple', 'Vulnerability welcome', 'Banyak feel emotionally open di fertile. Pasangan bisa receive vulnerability with grace.', '💝', 87),
('fertile', 'couple', 'Plan future together', 'Mood + clarity good. Talk vacation, life goals, financial plans yang need both.', '🗺️', 88),
('fertile', 'couple', 'No pressure script', 'Kalau pasangan sense expectation buat sex saat fertile, voice it gently. Pressure = killer libido.', '🎭', 89),

-- ===== Trivia + Lifestyle (11) =====
('fertile', 'trivia', 'Why "egg-white"?', 'Mucus saat fertile sama struktur sama putih telur — both protein-based, slippery, stretchy. Coincidence? Not really.', '🥚', 95),
('fertile', 'trivia', 'Sperm = marathon runner', 'Sperma 60 micrometers, swim 5 mm/min in mucus. Equivalent manusia swim 100 m in body length.', '🏊‍♂️', 96),
('fertile', 'trivia', 'Fertility awareness method', 'FAM = natural family planning method dengan track BBT + mucus + cycle. Failure rate 0.4-5% (typical use).', '📚', 97),
('fertile', 'trivia', 'Cervical mucus = invention', 'Body design cervical mucus to filter sperm — dead/abnormal sperm get caught, healthy ones pass.', '🛂', 98),

('fertile', 'lifestyle', 'Outfit confident', 'Confidence often peak fertile. Pakai outfit yang biasanya hesitate — feedback loop positive.', '👠', 105),
('fertile', 'lifestyle', 'Skincare highlight', 'Skin radiant naturally. Time invest di treatment yang biasa skip (mask, eye cream).', '💆‍♀️', 106),
('fertile', 'lifestyle', 'Music: sensual playlist', 'Slow R&B, romantic ballads, jazz. Mood matching.', '🎷', 107),
('fertile', 'lifestyle', 'Sensory awareness', 'Eat slowly, savor textures. Senses heightened — capitalize on small pleasures.', '🌶️', 108),
('fertile', 'lifestyle', 'Date night planning', 'Pasangan? Plan special. Solo? Plan special with self. Either way, this phase deserve celebration.', '🍷', 109),
('fertile', 'lifestyle', 'Photography mood', 'Light + glow self-photo at this phase often look best. Self-timer + mirror = confidence boost capture.', '📷', 110),
('fertile', 'lifestyle', 'Nature walk', 'Sense everything more vividly. Bunga, suara, angin. Nature appreciation often peak fertile.', '🌿', 111);
