-- Seed daily_insights — OVULATION + LUTEAL phases (~150 entries combined)

-- ============ OVULATION (~75 entries) ============

insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values
-- ===== Facts (24) =====
('ovulation', 'fact', 'Today: peak fertility', 'Egg released ~24 jam ago atau hari ini. Window konsepsi paling tinggi.', '🥚', 1),
('ovulation', 'fact', 'LH surge triggered it', 'Surge LH 24-36 jam lalu trigger follicle dominant pecah → egg released. Process taken minutes.', '⚡', 2),
('ovulation', 'fact', 'Egg viable 12-24 jam', 'Setelah keluar dari ovarium, egg viable cuma sehari. Itu kenapa fertility window tight.', '⏰', 3),
('ovulation', 'fact', 'Estrogen drop sharp', 'Setelah peak hari kemarin, estrogen drop ~50% dalam 24 jam. Bisa cause subtle mood shift.', '📉', 4),
('ovulation', 'fact', 'Progesteron starting', 'Corpus luteum (sisa follicle) mulai produce progesteron. Ini akan dominant 14 hari ke depan.', '📈', 5),
('ovulation', 'fact', 'BBT will rise', 'Progesteron raise BBT 0.3-0.5°C. Saat lo cek tomorrow morning, BBT lebih tinggi = ovulation confirmed.', '🌡️', 6),
('ovulation', 'fact', 'Mittelschmerz today', '15-20% feel sharp twinge sisi ovary yang ovulate. "Mittel" = middle (cycle), "schmerz" = pain.', '⚡', 7),
('ovulation', 'fact', 'Cervical mucus shift', 'Hari ini mucus reach peak (max stretchy). Besok mulai dry up — sign ovulation passed.', '💧', 8),
('ovulation', 'fact', 'Cervix max open', 'Cervix paling tinggi + soft + open. Tomorrow mulai turun + close.', '🚪', 9),
('ovulation', 'fact', 'Libido peak biological', 'Hormonal cocktail = max attraction + responsiveness. Body designed buat reproduction prime time.', '💕', 10),
('ovulation', 'fact', 'Body symmetry studies', 'Studi: face symmetry detection lebih akurat di ovulasi. Subconscious mate-quality assessment heightened.', '👥', 11),
('ovulation', 'fact', 'Smell preferences shift', 'Studi 2003: perempuan prefer scents associated dengan masculine MHC profile saat ovulation. Subtle but measurable.', '👃', 12),
('ovulation', 'fact', 'Voice subtly higher', 'Voice pitch slight rise saat ovulasi (Pipitone 2008). Mate-attraction signal cross-cultural.', '🎤', 13),
('ovulation', 'fact', 'Risk-taking complex', 'Counter-intuitively, risk-taking lebih conservative di ovulasi (Bröder 2003). Body protective mode.', '🛡️', 14),
('ovulation', 'fact', 'Twin probability up', 'Hari ini, kemungkinan ovulate 2 egg (= fraternal twins kalau both fertilized) max compared other days.', '👯', 15),
('ovulation', 'fact', 'Skin glow peak peak', 'Estrogen peak yesterday + circulation peak today = skin look "lit from within".', '✨', 16),
('ovulation', 'fact', 'Energy peak dual', 'Last day of follicular high-energy mood. Tomorrow body shift gear ke luteal recovery.', '🔋', 17),
('ovulation', 'fact', 'Cognitive: spatial', 'Spatial reasoning sedikit drop saat estrogen peak (Hampson 1990). Verbal masih sharp.', '🧩', 18),
('ovulation', 'fact', 'Egg journey', 'Egg released ke fimbriae fallopian tube → swept toward uterus over ~6-12 hari. Konsepsi happen di tube.', '🌀', 19),
('ovulation', 'fact', 'Progesteron warm body', 'Reason BBT naik = progesteron thermogenic. Bisa feel "warmer" atau lighter sweat saat tidur.', '🔥', 20),
('ovulation', 'fact', 'Ovulation = midpoint myth', 'Cuma akurat untuk 28-day cycle. Real ovulation = cycle_length - 14 days dari NEXT period start.', '🎯', 21),
('ovulation', 'fact', 'PCOS impact ovulasi', 'Polycystic Ovary Syndrome (PCOS) sering anovulatory atau irregular ovulation. Tracking still useful diagnostic.', '🩺', 22),
('ovulation', 'fact', 'Single egg per cycle', '99% of cycles release 1 egg. Both ovary alternate each cycle, tapi gak strictly. Body decide based on follicle maturation.', '🪞', 23),
('ovulation', 'fact', 'Tomorrow = ovulation passed', 'Body sign reverse: BBT up, mucus dry, cervix close. Verifying signs all retrospective. Track to learn pattern.', '📊', 24),

-- ===== Tips (18) =====
('ovulation', 'tip', 'Cek BBT besok pagi', 'Tonight = last low-temp night. Tomorrow temp jump = retrospective confirmation ovulation hari ini.', '🌡️', 30),
('ovulation', 'tip', 'Stay hydrated extra', 'Estrogen drop = subtle dehydration risk. Air putih cukup penting biar feeling stable.', '💧', 31),
('ovulation', 'tip', 'Note sensations', 'Mittelschmerz, breast tenderness, libido — note semua. Pattern recognition cycle ke cycle = skill.', '📝', 32),
('ovulation', 'tip', 'Magnesium proactive', 'Mulai supplement Mg 200-300mg. Bantu transition ke luteal smoother (kram + mood balance later).', '💊', 33),
('ovulation', 'tip', 'Last hard workout day', 'Body still anabolic-friendly. Strength workout besok masih OK; kalau bisa, capitalize hari ini.', '🏋️', 34),
('ovulation', 'tip', 'Date night romance', 'Libido peak + emotional openness = cocok plan special evening dengan pasangan.', '🍷', 35),
('ovulation', 'tip', 'Decision-making mode', 'Clarity + emotional intelligence good. Hard decision yang lo tunda? Address hari ini.', '🎯', 36),
('ovulation', 'tip', 'Backup contraception kalau avoiding', 'Ovulation hari = highest pregnancy risk (kalau ada sex without protection). Double up barrier method.', '🛡️', 37),
('ovulation', 'tip', 'Eat omega-3 rich', 'Salmon, walnut, chia. Omega-3 anti-inflammatory bantu body transisi ke luteal smoothly.', '🐟', 38),
('ovulation', 'tip', 'Sleep priority', 'Tonight quality sleep = recovery foundation untuk luteal. Skip caffeine after 2pm.', '😴', 39),
('ovulation', 'tip', 'Light dinner', 'Heavy meal tonight = digestion compete dengan body recovery. Light + nutrient-dense.', '🥗', 40),
('ovulation', 'tip', 'Reflect on energy', 'How''s lo''s body feel hari ini? Energy 1-10? Note. Compare cycle berikutnya — pattern.', '🪞', 41),
('ovulation', 'tip', 'Wind-down ritual', 'Tomorrow start luteal — body shift to slower mode. Ease in tonight: tea, warm bath, journal.', '🛀', 42),
('ovulation', 'tip', 'Plan luteal anticipation', 'Calendar luteal next 14 hari. Schedule hard task pre-PMS, easy task post-PMS. Plan with self.', '🗓️', 43),
('ovulation', 'tip', 'Affirmation today', '"Body lo lagi do something incredible." "Lo healthy + functioning well." Self-acknowledgment.', '🌟', 44),
('ovulation', 'tip', 'Check-in supporter', 'Kalau pasangan supporter aware ovulation phase, hari ini quality time. Communication peak.', '💬', 45),
('ovulation', 'tip', 'Capture energy', 'Photo, journal, voice note — capture vibes hari ini. Reference saat luteal feel down.', '📸', 46),
('ovulation', 'tip', 'Healthy sweet', 'Crave sweet starting? Dark chocolate >70%, fruit, atau honey-sweetened. Quality > quantity.', '🍓', 47),

-- ===== Support (10) =====
('ovulation', 'support', 'Today body peaks', 'Whatever lo plan atau gak plan, hari ini body lo accomplish biological miracle. Honor itu.', '🌟', 60),
('ovulation', 'support', 'Trust the process', 'Body knows what it''s doing. Lo gak harus interfere — just observe + appreciate.', '🌊', 61),
('ovulation', 'support', 'Energy honored', 'Lo merasa "on top of world" hari ini? Or "off-kilter"? Both valid. Body shifting mode.', '🌗', 62),
('ovulation', 'support', 'Beauty isn''t fertility', 'Hari ini lo glow karena estrogen peak. Tapi beauty lo gak diukur dari fertility status. Lo glow always.', '✨', 63),
('ovulation', 'support', 'Embrace the wave', 'High point of cycle. Tomorrow shifts to slower phase. Embrace flow, gak harus push it stay.', '🪷', 64),
('ovulation', 'support', 'Capacity to love', 'Hari ini emotional bandwidth max. Channel: pasangan, keluarga, teman, atau diri sendiri. Cinta = energi.', '💝', 65),
('ovulation', 'support', 'Whether trying or not', 'Trying konsepsi: hope. Avoiding: vigilance. Both equally valid relationship dengan body.', '🤲', 66),
('ovulation', 'support', 'Subtle sensations valid', 'Twinge sisi ovary, breast slight tender, mood subtle shift — lo gak imagining. Body real.', '👂', 67),
('ovulation', 'support', 'Permission to enjoy', 'Cycle feel like flowing? Permission untuk lean into joy. Gak perlu reason buat happy hari ini.', '🌻', 68),
('ovulation', 'support', 'Phase appreciation', 'Tiap phase punya gift. Ovulation = vibrancy + connection. Appreciate sebelum next phase comes.', '🎁', 69),

-- ===== Couple + Trivia + Lifestyle (23) =====
('ovulation', 'couple', 'Quality time tonight', 'Pasangan sense lo''s shift atau gak, plan time bareng. Energy + emotion availability max.', '👫', 80),
('ovulation', 'couple', 'Talk dreams', 'Long-term aspiration, family planning, life vision — kalau pasangan, today is the day.', '🌠', 81),
('ovulation', 'couple', 'Romantic dinner', 'Cook bareng atau dine out. Slower meal, conversation, eye contact. Connection focus.', '🍽️', 82),
('ovulation', 'couple', 'Physical touch', 'Cuddle, massage, slow dance. Touch perception heightened. Non-sexual touch equally valued.', '🤗', 83),
('ovulation', 'couple', 'Express appreciation', 'Tell pasangan something specific yang lo appreciate hari ini. Words have extra weight.', '💌', 84),
('ovulation', 'couple', 'Listen with full presence', 'Pasangan share something? Phone away, full attention. Active listening = love language.', '👂', 85),
('ovulation', 'couple', 'Birth control double-check', 'Avoiding konsepsi: pastiin contraception layered. Tracking + barrier optimal kombinasi.', '🔐', 86),
('ovulation', 'couple', 'Vulnerability welcome', 'Emotional openness max. If something on heart, today space buat share.', '💧', 87),

('ovulation', 'trivia', 'Ovulation predictor history', 'OPK home test dipopulerkan 1980s. Sebelumnya, BBT chart only — tedious + retrospective.', '📜', 95),
('ovulation', 'trivia', 'Mittelschmerz word', 'Coined 1840s by German doctor. Translation literal: "middle pain". Language exact.', '🇩🇪', 96),
('ovulation', 'trivia', 'Why 14 days luteal?', 'Corpus luteum lifespan 12-16 days kalau gak konsepsi. Programmed cell death = biological clock.', '⏳', 97),
('ovulation', 'trivia', 'Twin chance per ovulation', 'Spontaneous fraternal twin: 1 in 80 ovulation. Identical (same egg split): 1 in 250 — independent.', '👯‍♀️', 98),
('ovulation', 'trivia', 'Egg + sperm size', 'Egg = 0.1 mm (visible to naked eye). Sperm = 60 micrometers (microscopic). Egg 1000x bigger.', '📏', 99),

('ovulation', 'lifestyle', 'Special outfit', 'Glow + confidence peak. Wear something yang feel celebratory.', '👗', 105),
('ovulation', 'lifestyle', 'Skin care: gentle', 'Hari ini gak perlu agresif. Skin already at peak. Gentle cleanse + moisturize.', '🧖‍♀️', 106),
('ovulation', 'lifestyle', 'Music: passion', 'Lagu-lagu yang stir something. Whatever genre matches mood lo today.', '🎶', 107),
('ovulation', 'lifestyle', 'Connect with nature', 'Sunset walk, garden time, beach kalau bisa. Senses heightened amplify experience.', '🌅', 108),
('ovulation', 'lifestyle', 'Cook with love', 'Slow cooking, intentional meal prep. Either solo atau bareng pasangan, food jadi ritual.', '🍳', 109),
('ovulation', 'lifestyle', 'Photography candid', 'Self-portrait or with pasangan. Light hari ini often most flattering.', '📷', 110),
('ovulation', 'lifestyle', 'Read poetry', 'Emotional bandwidth open. Poetry hits deeper hari ini. Try Rumi, Mary Oliver, Sapardi.', '📖', 111),
('ovulation', 'lifestyle', 'Express creatively', 'Paint, write, dance — channel energy ke art. Physical or digital, doesn''t matter.', '🎨', 112);

-- ============ LUTEAL (~80 entries) ============

insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values
-- ===== Facts (25) =====
('luteal', 'fact', 'Luteal phase begins', 'Setelah ovulasi, body masuk luteal phase ~14 hari. Progesteron rising = different vibe dari follicular.', '🌒', 1),
('luteal', 'fact', 'Progesteron dominant', 'Hormone utama luteal. Stabilize endometrium kalau konsepsi terjadi. Kalau gak, drops trigger haid.', '📊', 2),
('luteal', 'fact', 'BBT elevated', 'BBT tetap tinggi sampai akhir luteal. Drop sharp = sign haid besoknya.', '🌡️', 3),
('luteal', 'fact', 'PMS = late luteal', 'Premenstrual syndrome biasanya hit 7-10 hari sebelum haid. Hormonal shift biological cause.', '⚠️', 4),
('luteal', 'fact', 'Energy gradual decrease', 'Beda dari follicular high-energy, luteal = pace lebih slow. Body shifting fokus ke recovery prep.', '🐢', 5),
('luteal', 'fact', 'Cravings explained', 'Progesteron + serotonin drop trigger crave carbs/sweets. Body seek serotonin precursors.', '🍫', 6),
('luteal', 'fact', 'Bloating physiology', 'Progesteron slow gut motility = constipation + bloat. Plus water retention. Both temporary.', '🎈', 7),
('luteal', 'fact', 'Breast tenderness common', 'Progesteron trigger ductal proliferation = breasts tender. Subside saat haid mulai.', '💗', 8),
('luteal', 'fact', 'Mood lability', 'Hormonal shift influence neurotransmitters. Mood swing valid biological, not "lebay".', '🌊', 9),
('luteal', 'fact', 'Sleep disturbed often', 'BBT tinggi disrupt sleep architecture. Wake more frequently, lighter sleep.', '😣', 10),
('luteal', 'fact', 'Skin breakouts', 'Progesteron + androgen rebalance = sebum production up. Common acne breakout late luteal.', '🔴', 11),
('luteal', 'fact', 'Anxiety spike possible', 'GABA system pengaruhi progesteron metabolite. Some experience anxiety up specifically luteal.', '😰', 12),
('luteal', 'fact', 'Headaches hormonal', 'Late luteal estrogen drop trigger menstrual migraine. Distinguish dari tension headache.', '🤕', 13),
('luteal', 'fact', 'Insulin sensitivity drops', 'Body less efficient processing carbs vs follicular. Steady protein + fiber meal lebih ideal.', '📉', 14),
('luteal', 'fact', 'Cortisol elevated', 'Stress response heightened di luteal. Same trigger feel "more stressful" than follicular.', '⚡', 15),
('luteal', 'fact', 'PMDD severe form', 'Premenstrual Dysphoric Disorder = severe PMS impacting daily function. 3-8% of menstruating people. Recognized DSM-5.', '🩺', 16),
('luteal', 'fact', 'Memory shift subtle', 'Recall slight slower vs follicular. Short-term memory tasks unchanged. Variable per person.', '🧠', 17),
('luteal', 'fact', 'Pain threshold lower', 'Estrogen drop = pain feels more intense. Same cramps level might rate higher pain scale.', '⚡', 18),
('luteal', 'fact', 'Libido drops gradual', 'Counter to follicular. Some experience sharp drop, others gradual. Both normal.', '💔', 19),
('luteal', 'fact', 'Body temp warmer', 'Sleep often need cooler bedroom. Layering bedding so easy adjust.', '🌡️', 20),
('luteal', 'fact', 'Period preview signs', '4-5 hari pre-haid: spot light, mucus brown/cream, breast tender max. Body wrap up.', '👀', 21),
('luteal', 'fact', 'Cervix lower closed', 'Cervix posisi turun + firm + closed di luteal. Opposite ovulation phase.', '⬇️', 22),
('luteal', 'fact', 'Why "luteal"', 'Dari "corpus luteum" — yellow body sisa follicle yang produce progesteron.', '🟡', 23),
('luteal', 'fact', 'PMDD treatment', 'SSRI (antidepressant), hormonal birth control, atau lifestyle intervention. Konsultasi profesional.', '💊', 24),
('luteal', 'fact', 'PMS ≠ all bad', 'Up to 75% experience PMS symptoms, biasanya mild. Severe (PMDD) cuma small subset. Tanpa stigma.', '⚖️', 25),

-- ===== Tips (18) =====
('luteal', 'tip', 'Slow down workout', 'Cardio LISS atau yoga > HIIT. Body lebih efficient di steady-state phase ini.', '🚶‍♀️', 30),
('luteal', 'tip', 'Magnesium for PMS', '300-400mg/day. Bantu mood + cramps + sleep. Glycinate form gentle for stomach.', '💊', 31),
('luteal', 'tip', 'Vitamin B6', 'Up to 100mg/day membantu PMS mood. Konsultasi dokter kalau supplement long-term.', '🌾', 32),
('luteal', 'tip', 'Reduce salt', 'Sodium tinggi amplify retensi air + bloat. Saltier processed food cut a bit.', '🚫', 33),
('luteal', 'tip', 'Increase fiber', 'Serat buat motility. 25-30g/day prevent luteal constipation. Apel, oat, lentil.', '🥬', 34),
('luteal', 'tip', 'Seed cycling (anecdotal)', 'Flax + pumpkin seeds di luteal half. Anecdotal practice — beberapa report subjective improvement.', '🌰', 35),
('luteal', 'tip', 'Restorative yoga', 'Forward folds, child pose, supine twist. Calming sympathetic nervous system.', '🧘', 36),
('luteal', 'tip', 'Sleep priority extra', 'Body extra disrupted. Earlier bedtime + dark room + consistent schedule.', '🌃', 37),
('luteal', 'tip', 'Hydrate with electrolytes', 'Plain water sometimes not enough. Coconut water atau pinch salt + lemon.', '🥥', 38),
('luteal', 'tip', 'Caffeine cap', 'Caffeine amplify anxiety + disrupt sleep. Cap 200mg/day di luteal half.', '☕', 39),
('luteal', 'tip', 'Schedule wisely', 'Big presentation? Schedule earlier in luteal (pre-PMS). Save late luteal buat low-cognitive load.', '🗓️', 40),
('luteal', 'tip', 'Comfort food intentional', 'Crave carbs? Choose complex carbs (oat, quinoa, sweet potato). Sustained energy > sugar spike.', '🍠', 41),
('luteal', 'tip', 'Lower expectations', 'OK kalau lo gak as productive late luteal. Adjust expectation matches phase capacity.', '📉', 42),
('luteal', 'tip', 'Boundaries firm', '"No" allowed kalau capacity gak ada. Saying yes pas low capacity = resentment later.', '🛑', 43),
('luteal', 'tip', 'Self-care non-negotiable', 'Bath, journal, gentle yoga. Mark calendar — luteal self-care = appointment dengan diri.', '🛁', 44),
('luteal', 'tip', 'Sunlight exposure', '10-15 menit sunlight pagi = bantu mood + sleep cycle. Especially helpful late luteal.', '☀️', 45),
('luteal', 'tip', 'Limit news/social', 'Cortisol-amplifying content avoid late luteal. Social media + news consumption mindful.', '📵', 46),
('luteal', 'tip', 'Connect with safe people', 'Talk to friend/family yang lo trust. Connection counter-balance luteal heaviness.', '📞', 47),

-- ===== Support (12) =====
('luteal', 'support', 'Slow is OK', 'Society push hustle, but body bilang slow. Dengarkan body — sustainable rhythm > burnout.', '🐢', 60),
('luteal', 'support', 'Mood is data, not identity', 'Lo yang feel down hari ini = real, tapi gak permanen. Phase ini akan lewat.', '🌗', 61),
('luteal', 'support', 'Cravings are info', 'Body seek something. Satisfy nourishing version when possible. No shame whatsoever.', '🥨', 62),
('luteal', 'support', 'Tiredness deserves rest', 'Badan capek = legitimate input. Bukan excuse, bukan weakness. Kasih response.', '😴', 63),
('luteal', 'support', 'Mood swing valid', 'Lo gak overreacting. Hormones real, neurotransmitters real. Body lagi shifting.', '🌊', 64),
('luteal', 'support', 'Honor low capacity', 'Lo bisa di follicular = lo masih sama orangnya di luteal. Output beda, value sama.', '⚖️', 65),
('luteal', 'support', 'Self-compassion practice', 'Talk to self like talk to best friend in struggle. Lembut, supportive, no harshness.', '🫂', 66),
('luteal', 'support', 'Nothing wrong with you', 'Luteal bukan malfunction. Itu phase rhythm. Lo functioning normally — sesuai siklus.', '🌗', 67),
('luteal', 'support', 'Stew if needed', 'Hari mau "hibernate" di kasur sambil scroll? Permission granted (occasionally). Comfort matters.', '🛏️', 68),
('luteal', 'support', 'Forgive small slips', 'Snap di pasangan? Skip workout? Body mode beda. Acknowledge, don''t spiral.', '🕊️', 69),
('luteal', 'support', 'Honor the descent', 'Kayak natural — fall season before winter. Luteal = emotional descent before reset.', '🍂', 70),
('luteal', 'support', 'Reset coming', 'Period start = reset. Cycle starts again. Lo akan feel reborn after a few hari haid.', '🌅', 71),

-- ===== Couple (10) =====
('luteal', 'couple', 'Patience needed', 'Pasangan supporter: pasangan lo possibly emotional luteal. Patience > advice.', '🤲', 80),
('luteal', 'couple', 'Don''t fix, just witness', 'Sometimes she/he doesn''t need solution. Just listen + acknowledge feelings valid.', '👂', 81),
('luteal', 'couple', 'Comfort food prep', 'Sup hangat, oatmeal, atau favorite comfort dish. Small gesture huge.', '🍲', 82),
('luteal', 'couple', 'Reduce stimulation', 'Kalau pasangan luteal sensitive, dim lights, lower volume, calm vibe.', '🪔', 83),
('luteal', 'couple', 'Touch consensual', 'Some need extra cuddle, others need space. Tanya, jangan asumsi.', '✋', 84),
('luteal', 'couple', 'Plan low-key dates', 'Movie at home > crowded restaurant. Match phase capacity.', '🎬', 85),
('luteal', 'couple', 'Take some load off', 'Cook, clean, errands. Reduce daily friction = significant support.', '🧹', 86),
('luteal', 'couple', 'Affirm value', '"Lo capable + valuable apa pun phase." Counter inner critic dengan external validation.', '💚', 87),
('luteal', 'couple', 'Avoid heavy talks', 'Important conversations? Schedule pasca-haid kalau bisa. Both clearer.', '⏸️', 88),
('luteal', 'couple', 'Solidarity gesture', 'Decaf together, early bedtime together. Solidarity = "lo gak alone in this".', '🤝', 89),

-- ===== Trivia + Lifestyle (15) =====
('luteal', 'trivia', '14-day luteal default', 'ACOG: luteal phase 12-16 hari. Kalau cycle 28 = ovulation hari 14. Cycle 35 = ovulation hari 21.', '📚', 95),
('luteal', 'trivia', 'PMS coined 1953', 'Term "premenstrual tension" by Greene + Dalton 1953. PMS officialy DSM 1994 (PMDD).', '📰', 96),
('luteal', 'trivia', 'Why crave salt', 'Aldosterone fluctuate di luteal = water balance shift. Body crave salty as compensatory.', '🧂', 97),
('luteal', 'trivia', 'Chocolate why crave', 'Dark chocolate magnesium + serotonin precursor + anti-inflammatory. Body intuitively know.', '🍫', 98),
('luteal', 'trivia', 'PMS in animals', 'Beberapa hewan show "premenstrual" behavioral changes — primates, dogs in heat. Hormonal across species.', '🐕', 99),

('luteal', 'lifestyle', 'Cozy outfit phase', 'Loose, comfy, layered. Skip restrictive waistbands. Body comfortable = mind comfortable.', '🧥', 105),
('luteal', 'lifestyle', 'Skin: simplify routine', 'Acne breakout common. Stick basics, don''t over-treat. Patience.', '🧴', 106),
('luteal', 'lifestyle', 'Music: chill playlist', 'Lo-fi, ambient, soft folk. Match phase mood.', '🎼', 107),
('luteal', 'lifestyle', 'Books: gentle genre', 'Cozy mystery, slow memoir, self-help digest. Save heavy literature for sharper phase.', '📖', 108),
('luteal', 'lifestyle', 'Bath ritual', 'Epsom salt (magnesium), lavender oil, warm water. 20 menit detox + relaxation.', '🛁', 109),
('luteal', 'lifestyle', 'Tea ritual evening', 'Chamomile, peppermint, ginger. Warm cup + book + early sleep = perfect luteal evening.', '🍵', 110),
('luteal', 'lifestyle', 'Slower morning', 'Skip alarm-rush. 5 menit stretching, slow coffee, intentional start.', '☕', 111),
('luteal', 'lifestyle', 'Journal feelings', 'Write down whatever come up. Externalizing emotions = relief. No structure required.', '📓', 112),
('luteal', 'lifestyle', 'Limit social plans', 'Mark calendar — late luteal = no social commitment if possible. Quality > quantity.', '🚪', 113),
('luteal', 'lifestyle', 'Plant care therapy', 'Water plants, prune, talk to them. Quiet ritual = grounding.', '🌱', 114);
