-- Migration 0022: Rewrite daily_insights catalog (Phase 5 K3)
-- =============================================================================
-- User feedback: copy lama terkesan AI-generated, banyak slang ("lo"),
-- em-dash berlebihan, emoji bertaburan, dan banyak konten "support" yang
-- vague (mirip ramalan zodiak).
--
-- Rewrite ini fokus:
--   - Tone formal-warm yang menyentuh perempuan ("Kamu", bukan "lo")
--   - Fakta scientific dengan mekanisme + angka spesifik
--   - Tip aktionable dengan dosis/durasi/instruksi konkret
--   - Trivia yang benar-benar menarik (cultural/historical fact)
--   - Lifestyle tips yang implementable
--   - Drop kategori "support" yang vague
--   - Drop em-dash, gunakan koma/titik/kolom
--   - Emoji minimal: hanya kalau relevan untuk visual aid
-- =============================================================================

-- Hapus seed lama
delete from public.daily_insights;

-- ============ PERIOD (75 entries) ============
insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values

-- ===== Fact (30) — physiology + medical info =====
('period', 'fact', 'Mengapa terjadi pendarahan?', 'Lapisan rahim (endometrium) yang dipersiapkan untuk implantasi luruh karena tidak ada pembuahan. Ini proses biologis yang sehat.', null, 1),
('period', 'fact', 'Volume haid normal', 'Rata-rata 30 sampai 80 ml per siklus. Lebih dari 80 ml disebut menorrhagia dan sebaiknya diperiksakan ke dokter.', null, 2),
('period', 'fact', 'Durasi haid yang sehat', 'ACOG menyatakan 2 sampai 7 hari masih normal. Kurang dari 2 hari atau lebih dari 7 hari patut diperhatikan.', null, 3),
('period', 'fact', 'Sumber kram haid', 'Prostaglandin memicu kontraksi rahim untuk meluruhkan endometrium. Kadar prostaglandin tinggi berkaitan dengan kram lebih intens.', null, 4),
('period', 'fact', 'Hormon turun drastis', 'Estrogen dan progesteron turun di awal haid. Penurunan ini memengaruhi mood, energi, dan libido.', null, 5),
('period', 'fact', 'Kehilangan zat besi', 'Setiap siklus haid melepas sekitar 15 mg zat besi. Itu sebabnya konsumsi makanan tinggi zat besi penting di periode ini.', null, 6),
('period', 'fact', 'Ketebalan endometrium', 'Sebelum haid, lapisan rahim bisa setebal 8 sampai 16 mm. Saat haid berlangsung, ketebalan turun menjadi sekitar 3 mm.', null, 7),
('period', 'fact', 'PMS dan PMDD berbeda', 'PMS umum dan ringan. PMDD (Premenstrual Dysphoric Disorder) parah dan mengganggu kegiatan harian. PMDD memengaruhi 3 sampai 8 persen perempuan.', null, 8),
('period', 'fact', 'Variasi warna darah haid', 'Merah cerah berarti darah segar, gelap atau coklat berarti darah lebih lama di rahim. Coklat di awal atau akhir haid umumnya normal.', null, 9),
('period', 'fact', 'Kram patologis', 'Selain prostaglandin, endometriosis dan fibroid uterus dapat menyebabkan kram parah. Konsultasi jika kram mengganggu kegiatan harian.', null, 10),
('period', 'fact', 'Haid sebagai tanda vital', 'American Academy of Pediatrics menetapkan haid sebagai vital sign kelima. Pola siklus mencerminkan kesehatan tubuh secara umum.', null, 11),
('period', 'fact', 'Tanda anemia', 'Lemas berlebihan, pucat, jantung berdebar saat haid bisa menjadi tanda anemia. Periksa kadar hemoglobin jika gejala berulang.', null, 12),
('period', 'fact', 'Kapan ovulasi terjadi', 'Sekitar 14 hari sebelum haid berikutnya, bukan 14 hari setelah haid mulai (kecuali siklus 28 hari).', null, 13),
('period', 'fact', 'Bekuan darah saat haid', 'Bekuan kecil di bawah 2 cm saat haid berat masih normal. Bekuan besar atau sering perlu pemeriksaan.', null, 14),
('period', 'fact', 'Stres memengaruhi siklus', 'Stres dapat menunda ovulasi sehingga siklus jadi lebih panjang. Yang berubah karena stres adalah waktu ovulasi, bukan haid sendiri.', null, 15),
('period', 'fact', 'Sakit kepala saat haid', 'Penurunan estrogen dapat memicu menstrual migraine. Magnesium 400 mg per hari dan hidrasi cukup membantu mengurangi frekuensi.', null, 16),
('period', 'fact', 'Mood swing dari hormon', 'Penurunan hormonal di akhir luteal hingga awal haid memengaruhi serotonin di otak. Ini reaksi biokimia, bukan emosi yang dilebih-lebihkan.', null, 17),
('period', 'fact', 'Vitamin C bantu zat besi', 'Vitamin C meningkatkan absorpsi zat besi 3 hingga 6 kali lipat. Konsumsi jeruk dan bayam bersamaan untuk hasil optimal.', null, 18),
('period', 'fact', 'Kafein dan kram', 'Kafein menyempitkan pembuluh darah sehingga kram terasa lebih sakit. Pertimbangkan mengurangi 1 atau 2 hari pertama haid.', null, 19),
('period', 'fact', 'Olahraga ringan menolong', 'Olahraga ringan melepas endorfin yang berfungsi sebagai pereda nyeri alami. Yoga atau jalan kaki 20 menit dapat mengurangi kram hingga 25 persen.', null, 20),
('period', 'fact', 'Cycle sync mitos', 'Studi besar di Oxford 2017 menyimpulkan sinkronisasi siklus antar teman serumah lebih banyak kebetulan, bukan biological synchronization.', null, 21),
('period', 'fact', 'Kompres hangat efektif', 'Penelitian 2012 menunjukkan kompres hangat 40 derajat Celsius di perut bawah dapat mengurangi kram seefektif ibuprofen.', null, 22),
('period', 'fact', 'Pilihan produk haid', 'Cup haid bisa dipakai 8 sampai 12 jam dan lebih hemat. Tampon maksimal 8 jam dengan risiko TSS. Pad pilihan paling sederhana.', null, 23),
('period', 'fact', 'Hewan yang juga haid', 'Hanya sekitar 85 spesies mamalia mengalami haid, di antaranya manusia, primata, kelelawar, dan gajah. Sisanya menyerap kembali endometrium.', null, 24),
('period', 'fact', 'Sindrom syok toksik', 'Toxic Shock Syndrome (TSS) jarang tapi serius. Risiko meningkat jika tampon dipakai lebih dari 8 jam. Ganti rutin.', null, 25),
('period', 'fact', 'Kapan menarche normal', 'Haid pertama (menarche) biasanya terjadi di usia 12 sampai 13 tahun. Menarche kurang dari 9 atau lebih dari 16 tahun perlu evaluasi.', null, 26),
('period', 'fact', 'Vitamin D dan PMS', 'Studi menunjukkan kadar vitamin D rendah berkaitan dengan PMS lebih parah. Cek kadar 25(OH)D jika PMS terus mengganggu.', null, 27),
('period', 'fact', 'Olahan trans fat memperburuk', 'Asam lemak trans (margarin, gorengan industri) meningkatkan inflamasi yang memperparah kram. Hindari di hari haid.', null, 28),
('period', 'fact', 'Rahim sebesar buah pir', 'Ukuran rahim normal sekitar 7 cm panjang dengan berat 60 gram. Saat hamil bisa berkembang lebih dari 1 kg.', null, 29),
('period', 'fact', 'Tidur dan haid', 'Suhu inti tubuh turun saat haid sehingga tidur bisa lebih nyenyak. Kram dapat mengganggu, gunakan posisi miring dengan bantal di antara lutut.', null, 30),

-- ===== Tip (25) — actionable =====
('period', 'tip', 'Kompres hangat 15 menit', 'Letakkan botol air hangat atau heating pad di perut bawah selama 15 sampai 20 menit. Bisa diulang setiap 2 jam.', null, 50),
('period', 'tip', 'Magnesium untuk kram', 'Magnesium glycinate 200 sampai 400 mg per hari membantu mengurangi kram. Sumber alami: almond, dark chocolate, dan bayam.', null, 51),
('period', 'tip', 'Cukupi cairan 2,5 liter', 'Konsumsi air putih 2,5 liter per hari saat haid mengurangi bloating dan retensi cairan.', null, 52),
('period', 'tip', 'Posisi tidur paling nyaman', 'Tidur miring ke kiri dengan bantal di antara lutut mengurangi tekanan di perut bawah dan punggung.', null, 53),
('period', 'tip', 'Yoga child pose dan cat-cow', 'Pose lembut seperti child pose, cat-cow, dan supine twist mengurangi tekanan di pelvis. Hindari pose terbalik (inversi).', null, 54),
('period', 'tip', 'Dark chocolate 70 persen', 'Mengandung magnesium, antioksidan, dan memicu pelepasan endorfin. Konsumsi 1 sampai 2 kotak (20 gram) cukup.', null, 55),
('period', 'tip', 'Kurangi makanan asin', 'Sodium tinggi memperparah retensi air dan bloating. Hindari ramen instan, keripik, dan makanan olahan di hari haid.', null, 56),
('period', 'tip', 'Jalan kaki 20 menit', 'Aktivitas ringan lebih baik daripada hanya berbaring. Jalan kaki 20 menit cukup untuk memicu endorfin.', null, 57),
('period', 'tip', 'Ibuprofen profilaktik', 'Mulai konsumsi ibuprofen sesuai anjuran 1 sampai 2 hari sebelum haid lebih efektif daripada menunggu sakit muncul.', null, 58),
('period', 'tip', 'Period underwear absorben', 'Celana dalam khusus haid (Modibodi, Thinx) bisa menggantikan pad untuk hari ringan. Lebih ramah lingkungan dan nyaman.', null, 59),
('period', 'tip', 'Teh chamomile dan jahe', 'Chamomile melemaskan otot, jahe bersifat anti-inflamasi. Seduh hangat sebelum tidur untuk meredakan kram.', null, 60),
('period', 'tip', 'Pilihan kaya zat besi', 'Hati ayam, daging merah, bayam, lentil, dan tahu kaya zat besi. Kombinasikan dengan vitamin C agar absorpsi maksimal.', null, 61),
('period', 'tip', 'Skincare disederhanakan', 'Pori cenderung lebih terbuka saat haid. Gunakan rutinitas dasar saja, hindari eksfoliator agresif.', null, 62),
('period', 'tip', 'Tidur 8 sampai 9 jam', 'Tubuh sedang dalam mode pemulihan ekstra. Tambahan 1 sampai 2 jam tidur dibanding hari biasa membantu.', null, 63),
('period', 'tip', 'Kurangi blue light malam', 'Layar gadget mengganggu produksi melatonin. Matikan perangkat 1 jam sebelum tidur untuk tidur berkualitas.', null, 64),
('period', 'tip', 'Pakaian longgar nyaman', 'Hindari celana ketat dan ikat pinggang elastis ketat. Loose pants, kaftan, atau dress lebih ramah saat haid.', null, 65),
('period', 'tip', 'Sup hangat berprotein', 'Sup ayam, soto, atau bone broth memberikan hidrasi, protein, dan kenyamanan. Cairan hangat membantu absorpsi nutrisi.', null, 66),
('period', 'tip', 'Coba TENS unit', 'Mesin TENS kecil (Rp 200 sampai 500 ribu) memberikan stimulasi listrik di perut bawah untuk meredakan kram. Efektif tanpa obat.', null, 67),
('period', 'tip', 'Kompres punggung bawah', 'Selain perut, kompres hangat di punggung bawah membantu meredakan nyeri yang menjalar saat haid.', null, 68),
('period', 'tip', 'Atur jadwal hari ini', 'Tidak harus skip pekerjaan, tapi prioritaskan tugas yang ringan secara mental. Jadwalkan meeting penting di hari berikutnya.', null, 69),
('period', 'tip', 'Vitamin B6 untuk PMS', 'Vitamin B6 50 sampai 100 mg per hari membantu meredakan PMS mood. Konsultasikan dokter untuk konsumsi jangka panjang.', null, 70),
('period', 'tip', 'Probiotik untuk pencernaan', 'Probiotik mendukung kesehatan usus yang sering terganggu saat haid. Yogurt atau suplemen multi-strain dapat membantu.', null, 71),
('period', 'tip', 'Hindari alkohol', 'Alkohol memperburuk dehidrasi dan inflamasi. Tunda 2 sampai 3 hari pertama haid untuk meredakan gejala.', null, 72),
('period', 'tip', 'Bath garam epsom', 'Berendam dengan 1 cangkir garam epsom (mengandung magnesium) selama 20 menit membantu meredakan kram dan tegangan otot.', null, 73),
('period', 'tip', 'Catat pola untuk pola', 'Catat hari ini: intensitas kram (1-10), durasi haid, gejala dominan. 3 sampai 6 siklus akan membentuk pola personal Kamu.', null, 74),

-- ===== Trivia (8) =====
('period', 'trivia', 'Sejarah produk haid', 'Mesir kuno memakai papirus yang dilembutkan, Romawi memakai wool, Yunani memakai linen. Tampon modern baru ditemukan tahun 1933.', null, 90),
('period', 'trivia', 'Cuti haid di Asia', 'Jepang menetapkan cuti haid sejak 1947. Korea Selatan, Indonesia, dan Taiwan juga memiliki ketentuan serupa di UU ketenagakerjaan.', null, 91),
('period', 'trivia', 'Pajak produk haid', 'Banyak negara mengenakan PPN pada pad dan tampon. India menghapuskan tahun 2018, Skotlandia menyediakan gratis sejak 2020.', null, 92),
('period', 'trivia', 'Usia menarche menurun', 'Usia menarche rata-rata menurun dari 16 tahun (1860) menjadi 12 tahun (sekarang). Faktor: gizi membaik dan lingkungan.', null, 93),
('period', 'trivia', 'Etimologi menstruasi', 'Kata menstruation dari bahasa Latin mensis (bulan). Banyak budaya kuno mengaitkan siklus dengan bulan, meski sains modern tidak menemukan korelasi.', null, 94),
('period', 'trivia', 'Anggaran haid seumur hidup', 'Rata-rata perempuan mengalami sekitar 450 siklus haid seumur hidup, total sekitar 6 sampai 7 tahun haid.', null, 95),
('period', 'trivia', 'Kapan ginekolog menemukan PMS', 'Istilah Premenstrual Tension diperkenalkan oleh Greene dan Dalton tahun 1953. PMDD baru masuk DSM-5 tahun 1994.', null, 96),
('period', 'trivia', 'Negara pertama bebas pad', 'Skotlandia tahun 2020 menjadi negara pertama yang menjamin akses gratis ke produk haid bagi semua warga.', null, 97),

-- ===== Lifestyle (12) =====
('period', 'lifestyle', 'Olahraga disesuaikan', 'Ganti HIIT dengan yoga atau pilates ringan. Tubuh dalam fase pemulihan, bukan waktu mendorong batas.', null, 110),
('period', 'lifestyle', 'Riasan minimalis', 'Pori lebih terbuka saat haid sehingga makeup lebih cepat menyumbat. Pertimbangkan minimal makeup days.', null, 111),
('period', 'lifestyle', 'Rencana hari istirahat', 'Sarung, teh hangat, buku ringan, podcast favorit. Susun hari istirahat yang Kamu nantikan.', null, 112),
('period', 'lifestyle', 'Playlist khusus', 'Buat playlist musik lembut dan slow yang Kamu putar khusus saat haid. Asosiasi musik dengan mood membantu relaksasi.', null, 113),
('period', 'lifestyle', 'Aromaterapi lavender', 'Essential oil lavender, peppermint, atau clary sage di diffuser membantu mengurangi tegangan. Lavender favorit untuk relaksasi.', null, 114),
('period', 'lifestyle', 'Stok perlengkapan haid', 'Siapkan kotak khusus berisi pad, tampon, painkiller, dan teh chamomile. Mengurangi friksi mengambil sesuatu saat sakit.', null, 115),
('period', 'lifestyle', 'Jurnal singkat', 'Catat 3 hal: bagaimana mood hari ini (1-10), apa yang dimakan, durasi tidur. Pola muncul setelah beberapa siklus.', null, 116),
('period', 'lifestyle', 'Streaming pilihan', 'Pilih tontonan ringan dan menyenangkan, hindari konten berat secara emosional. Body sedang sensitif.', null, 117),
('period', 'lifestyle', 'Sepatu nyaman', 'Hindari heels atau sepatu sempit. Sneakers atau flats membantu mengurangi tegangan punggung yang sudah pegal.', null, 118),
('period', 'lifestyle', 'Pijat lembut sendiri', 'Pijat perut bawah dengan minyak hangat searah jarum jam selama 5 menit membantu meredakan kram.', null, 119),
('period', 'lifestyle', 'Kurangi multitasking', 'Konsentrasi turun saat haid. Selesaikan satu tugas sebelum pindah agar pekerjaan terasa lebih mudah.', null, 120),
('period', 'lifestyle', 'Jalan pagi 10 menit', 'Sinar matahari pagi 10 menit membantu mood dan ritme sirkadian. Tidak perlu lama, konsistensi yang penting.', null, 121);

-- ============ FOLLICULAR (75 entries) ============
insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values

-- ===== Fact (30) =====
('follicular', 'fact', 'Fase folikular dimulai', 'Setelah haid, follicle di ovarium mulai matang. Estrogen naik bertahap memulihkan energi dan mood.', null, 1),
('follicular', 'fact', 'Estrogen naik bertahap', 'Estrogen mulai meningkat 5 sampai 7 hari setelah haid mulai. Mood dan energi biasanya naik secara linear.', null, 2),
('follicular', 'fact', 'Fase kognitif terbaik', 'Studi 2014: fungsi kognitif dan kelancaran verbal lebih baik di fase folikular. Cocok untuk tugas baru atau pembelajaran.', null, 3),
('follicular', 'fact', 'Kulit tampak glowing', 'Estrogen yang meningkat memicu produksi kolagen. Kulit cenderung tampak lebih kenyal dan bercahaya.', null, 4),
('follicular', 'fact', 'Sensasi kram terlupakan', 'Reset endorfin pasca-haid plus shift hormonal membuat kram terasa seperti kenangan jauh.', null, 5),
('follicular', 'fact', 'Kapasitas latihan tinggi', 'Kekuatan dan daya tahan dapat mencapai puncak di akhir folikular. Estrogen mendukung sintesis protein otot.', null, 6),
('follicular', 'fact', 'LH masih rendah', 'Luteinizing Hormone (LH) baru melonjak menjelang ovulasi. Selama folikular, LH stabil di kadar rendah.', null, 7),
('follicular', 'fact', 'FSH peran utama', 'Follicle Stimulating Hormone (FSH) memicu pematangan sel telur di ovarium dan meningkat di awal folikular.', null, 8),
('follicular', 'fact', 'Lendir serviks berubah', 'Awal folikular: lendir kering atau lengket. Akhir folikular: lendir krim hingga basah, sebagai pratinjau jendela subur.', null, 9),
('follicular', 'fact', 'Suhu basal tubuh rendah', 'BBT (Basal Body Temperature) sekitar 36,1 sampai 36,4 derajat Celsius selama folikular. Akan naik saat ovulasi.', null, 10),
('follicular', 'fact', 'Jendela subur mendekat', 'Jendela subur mulai sekitar 5 hari sebelum ovulasi. Akhir folikular menandakan pintu jendela subur.', null, 11),
('follicular', 'fact', 'Otak lebih aktif', 'Pencitraan fMRI menunjukkan aktivitas hippocampus dan prefrontal cortex meningkat saat estrogen tinggi.', null, 12),
('follicular', 'fact', 'Mood dasar lebih cerah', 'Serotonin lebih tersedia ketika estrogen tinggi. Mood dasar cenderung lebih baik di fase ini.', null, 13),
('follicular', 'fact', 'Sensitivitas insulin naik', 'Tubuh lebih efisien memproses karbohidrat di folikular. Asupan karbo dimanfaatkan lebih baik.', null, 14),
('follicular', 'fact', 'Pertumbuhan rambut', 'Estrogen memperpanjang fase pertumbuhan rambut. Rambut terasa lebih tebal dan sehat di fase ini.', null, 15),
('follicular', 'fact', 'Suara sedikit naik', 'Studi 2008: pitch suara perempuan sedikit naik ketika estrogen tinggi. Perubahan halus tapi konsisten.', null, 16),
('follicular', 'fact', 'Energi awet muda', 'Banyak perempuan menggambarkan energi akhir folikular seperti kembali ke usia 18 tahun. Estrogen yang berperan.', null, 17),
('follicular', 'fact', 'Toleransi stres lebih baik', 'Respons kortisol lebih terkendali di folikular dibanding luteal. Fase tepat untuk tugas yang penuh tekanan.', null, 18),
('follicular', 'fact', 'Tidur lebih dalam', 'BBT yang lebih rendah memberikan kualitas tidur lebih restoratif. Kuantitas penting tetap dijaga 7 sampai 9 jam.', null, 19),
('follicular', 'fact', 'Ambang nyeri lebih tinggi', 'Estrogen memodulasi persepsi nyeri. Rasa sakit yang sama terasa kurang intens dibanding di luteal.', null, 20),
('follicular', 'fact', 'Memori verbal puncak', 'Recall dan word retrieval lebih baik saat estrogen tinggi (Hampson 1990). Cocok untuk presentasi atau ujian lisan.', null, 21),
('follicular', 'fact', 'Estrogen dan dopamin', 'Estrogen meningkatkan sinyal dopamin di otak, sehingga motivasi dan rasa reward terasa lebih kuat.', null, 22),
('follicular', 'fact', 'Tahap proliferasi', 'Endometrium memasuki tahap proliferasi: lapisan rahim menebal kembali sebagai persiapan implantasi potensial.', null, 23),
('follicular', 'fact', 'Sebum berkurang', 'Estrogen menekan produksi sebum, sehingga kulit terasa kurang berminyak dibanding fase lain.', null, 24),
('follicular', 'fact', 'Dominasi belahan otak kanan', 'Studi neuroscience: di fase folikular, perempuan cenderung lebih intuitif dan kreatif (dominasi otak kanan).', null, 25),
('follicular', 'fact', 'Resistensi sel imun', 'Imunitas sedang meningkat di fase ini. Tubuh lebih siap melawan infeksi ringan.', null, 26),
('follicular', 'fact', 'Variasi lama folikular', 'Fase folikular paling bervariasi (10 sampai 22 hari). Inilah penyebab utama variasi panjang siklus.', null, 27),
('follicular', 'fact', 'Estradiol versi paling aktif', 'Dari tiga jenis estrogen (estradiol, estriol, estrone), estradiol paling aktif dan dominan di tahun reproduktif.', null, 28),
('follicular', 'fact', 'Dampak puasa', 'Intermittent fasting umumnya lebih ditoleransi di folikular. Avoid extended fasting di luteal.', null, 29),
('follicular', 'fact', 'Adaptasi kafein', 'Sensitivitas kafein lebih rendah di folikular. Toleransi konsumsi kafein cenderung lebih baik di fase ini.', null, 30),

-- ===== Tip (25) =====
('follicular', 'tip', 'Mulai proyek baru', 'Mood, energi, dan kognisi mendukung. Mulai proyek yang sempat tertunda atau pelajari skill baru.', null, 50),
('follicular', 'tip', 'Latihan kekuatan', 'Fase paling cocok untuk angkat beban berat. Tubuh membangun otot lebih efisien dengan dukungan estrogen.', null, 51),
('follicular', 'tip', 'Jadwalkan meeting penting', 'Kelancaran verbal dan keberanian sosial puncak. Presentasi, negosiasi, dan acara sosial paling baik di fase ini.', null, 52),
('follicular', 'tip', 'Coba resep baru', 'Selera petualang sedang aktif. Kalau biasanya picky, sekarang waktunya mencoba sesuatu yang baru.', null, 53),
('follicular', 'tip', 'Meal prep ke depan', 'Energi dan klaritas mendukung. Siapkan makanan untuk minggu luteal saat tubuh akan lebih lelah.', null, 54),
('follicular', 'tip', 'Aktif sosial', 'Rencanakan hangout, dinner, atau networking. Folikular adalah puncak bandwidth sosial.', null, 55),
('follicular', 'tip', 'Pelajari skill baru', 'Otak dalam mode menyerap. Manfaatkan untuk online course, language app, atau coding tutorial.', null, 56),
('follicular', 'tip', 'Cardio performa puncak', 'VO2 max sedikit lebih tinggi. Cocok untuk lari, HIIT, atau cycling personal record.', null, 57),
('follicular', 'tip', 'Eksperimen skincare', 'Kulit responsif terhadap active ingredients. Saat tepat memperkenalkan retinol atau AHA secara bertahap.', null, 58),
('follicular', 'tip', 'Bersih-bersih besar', 'Energi dan ketegasan mendukung. Saat tepat untuk decluttering, donate barang, atau organize closet.', null, 59),
('follicular', 'tip', 'Brunch dengan teman', 'Mood baik secara alami. Jadwalkan quality time dengan orang yang Kamu sayang.', null, 60),
('follicular', 'tip', 'Negosiasi gaji', 'Kepercayaan diri dan artikulasi puncak. Ajukan promosi atau kenaikan gaji jika memungkinkan memilih waktu.', null, 61),
('follicular', 'tip', 'Rencana date romantis', 'Libido mulai naik. Rencana romantis, outfit cantik, ide date semua selaras.', null, 62),
('follicular', 'tip', 'Asupan protein cukup', 'Sintesis otot lebih tinggi. Pastikan protein 1,6 sampai 2 g per kg berat badan untuk capitalize folikular.', null, 63),
('follicular', 'tip', 'Hidrasi konsisten', 'Fase aktif berarti pergantian cairan lebih cepat. Target 2,5 sampai 3 liter per hari.', null, 64),
('follicular', 'tip', 'Cold exposure', 'Toleransi mandi air dingin atau ice bath lebih tinggi. Membantu memicu dopamin dan respons imun.', null, 65),
('follicular', 'tip', 'Brainstorm ide besar', 'Berjalan dengan pena dan kertas. Kreativitas mengalir, ide datang sendiri. Tangkap sebelum lupa.', null, 66),
('follicular', 'tip', 'Tetap konsisten tidur', '7 sampai 9 jam tetap penting walau merasa tidak butuh banyak tidur. Jangan korbankan tidur hanya karena merasa kuat.', null, 67),
('follicular', 'tip', 'Tanya pertanyaan sulit', 'Percakapan sulit, meeting umpan balik, negosiasi rumit selaras dengan regulasi emosi yang baik di fase ini.', null, 68),
('follicular', 'tip', 'Latih mindfulness', 'Otot meditasi yang dibangun di folikular jadi bekal saat luteal. Investasi yang berbayar.', null, 69),
('follicular', 'tip', 'Lari pagi', 'Pagi cerah dengan endorfin tinggi. Lari 20 sampai 30 menit memberi mood boost yang bertahan seharian.', null, 70),
('follicular', 'tip', 'Jurnal target', 'Tulis 3 target mingguan. Klaritas mental mendukung perencanaan jangka pendek yang realistis.', null, 71),
('follicular', 'tip', 'Coba cooking class', 'Belajar masakan baru lebih mudah saat kognisi tinggi. Bisa solo atau dengan pasangan.', null, 72),
('follicular', 'tip', 'Networking event', 'Energi sosial puncak. Hadir ke meetup, conference, atau workshop tanpa kelelahan berlebihan.', null, 73),
('follicular', 'tip', 'Investasi belajar bahasa', 'Otak menyerap pola bahasa lebih baik. 15 menit per hari di Duolingo atau aplikasi serupa berdampak signifikan.', null, 74),

-- ===== Trivia (8) =====
('follicular', 'trivia', 'Etimologi follicle', 'Dari bahasa Latin folliculus yang berarti kantong kecil. Follicle ovarium adalah kantong kecil tempat sel telur matang.', null, 90),
('follicular', 'trivia', 'Jumlah follicle awal', 'Setiap siklus, 15 sampai 20 follicle mulai matang di kedua ovarium. Hanya 1 (jarang 2) yang dominant dan berovulasi.', null, 91),
('follicular', 'trivia', 'Atresia follicle', 'Follicle yang tidak terpilih mengalami atresia (degenerasi). Tubuh memilih yang paling fit dalam seleksi alami biologis.', null, 92),
('follicular', 'trivia', 'Cadangan sel telur', 'Saat lahir, perempuan punya 1 sampai 2 juta telur. Saat pubertas tinggal 300 sampai 400 ribu. Setiap siklus 1000+ habis.', null, 93),
('follicular', 'trivia', 'Tiga jenis estrogen', 'Estradiol (E2): dominan di tahun reproduktif. Estriol (E3): dominan di kehamilan. Estrone (E1): dominan pasca-menopause.', null, 94),
('follicular', 'trivia', 'AMH sebagai indikator', 'Anti-Müllerian Hormone (AMH) menjadi indikator cadangan sel telur. Kadar AMH menurun seiring usia.', null, 95),
('follicular', 'trivia', 'Periode terpendek', 'Tercatat dalam literatur, fase folikular terpendek 10 hari masih dianggap normal jika konsisten.', null, 96),
('follicular', 'trivia', 'Pelopor penelitian siklus', 'Dr. Kyusaku Ogino dan Dr. Hermann Knaus secara independen menemukan metode kalender ovulasi pada tahun 1924 dan 1932.', null, 97),

-- ===== Lifestyle (12) =====
('follicular', 'lifestyle', 'Outfit lebih berani', 'Mood adventurous, coba outfit yang biasa Kamu ragu pakai. Warna, motif, statement piece.', null, 110),
('follicular', 'lifestyle', 'Konsisten skincare', 'Saat untuk konsisten dengan rutinitas. Hasilnya akan terkumpul.', null, 111),
('follicular', 'lifestyle', 'Playlist energik', 'Pop, dance, fun. Selaras dengan mood yang naturally cheerful.', null, 112),
('follicular', 'lifestyle', 'Outdoor lebih dari indoor', 'Sinar matahari dan udara segar memperkuat mood boost dari estrogen. Jalan, piknik, atau kerja di taman.', null, 113),
('follicular', 'lifestyle', 'Coba standing desk', 'Energi cukup untuk posisi alternated. Menjaga punggung, membakar kalori, lebih produktif.', null, 114),
('follicular', 'lifestyle', 'Booking dokter', 'Energi dan organisasi memuncak. Booking appointment dokter, dokter gigi, atau mata yang sempat tertunda.', null, 115),
('follicular', 'lifestyle', 'Tantangan baca', 'Kognisi tajam dan rasa ingin tahu tinggi. Mulai buku panjang yang biasanya intimidating.', null, 116),
('follicular', 'lifestyle', 'Rawat tanaman', 'Repot, prune, fertilize tanaman. Care plus nature time double therapeutic.', null, 117),
('follicular', 'lifestyle', 'Eksplorasi cafe baru', 'Coba cafe atau restoran yang belum pernah dikunjungi. Kombinasikan dengan bekerja remote untuk variasi.', null, 118),
('follicular', 'lifestyle', 'Photoshoot pribadi', 'Confidence puncak. Self-portrait dengan timer di tempat menarik untuk dokumentasi mood baik.', null, 119),
('follicular', 'lifestyle', 'Volunteer atau komunitas', 'Energi sosial cukup untuk berkontribusi. Volunteer di komunitas atau bantu teman pindahan.', null, 120),
('follicular', 'lifestyle', 'Mulai hobi kreatif', 'Painting, knitting, atau crafting. Folikular membangkitkan kreativitas yang biasanya terpendam.', null, 121);

-- ============ FERTILE (75 entries) ============
insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values

-- ===== Fact (30) =====
('fertile', 'fact', 'Jendela subur dimulai', 'Sperma dapat bertahan 5 hari dalam tubuh. Ditambah sel telur viable 24 jam saat ovulasi, jendela konsepsi mencakup 6 hari.', null, 1),
('fertile', 'fact', 'Lendir serviks indikator', 'Lendir berubah menjadi seperti putih telur: bening, kenyal, dan licin. Tanda tubuh siap konsepsi.', null, 2),
('fertile', 'fact', 'Posisi serviks naik', 'Serviks naik lebih tinggi, menjadi lebih lunak dan terbuka. Jika dicek manual, beda jelas dari hari biasa.', null, 3),
('fertile', 'fact', 'BBT belum naik', 'Suhu basal masih rendah di fertile window pre-ovulasi. Naik baru setelah ovulasi.', null, 4),
('fertile', 'fact', 'LH mulai naik', 'Luteinizing Hormone mulai meningkat 24 sampai 36 jam sebelum ovulasi. LH test strip menjadi positif.', null, 5),
('fertile', 'fact', 'Estrogen puncak', 'Estrogen mencapai puncak sekitar 1 hari sebelum ovulasi. Inilah yang memicu lonjakan LH.', null, 6),
('fertile', 'fact', 'Libido naik alami', 'Cocktail hormonal di fertile membuat libido meningkat secara biologis. Tubuh secara natural mengarah ke aktivitas reproduksi.', null, 7),
('fertile', 'fact', 'Mittelschmerz', 'Sekitar 15 sampai 20 persen perempuan merasakan nyeri ringan di sisi ovarium yang berovulasi. Sharp twinge atau dull ache, beberapa jam.', null, 8),
('fertile', 'fact', 'Glow kulit puncak', 'Estrogen, progesteron seimbang, sirkulasi naik. Banyak perempuan tampak best skin di fertile window.', null, 9),
('fertile', 'fact', 'Probabilitas konsepsi', 'Hari minus 2 sebelum ovulasi: 33 persen kemungkinan konsepsi (puncak). Hari ovulasi: 27 persen. Drop drastis setelahnya.', null, 10),
('fertile', 'fact', 'Daya hidup sperma 5 hari', 'Sperma dalam lendir serviks fertile bisa bertahan hingga 5 hari. Itu sebabnya jendela subur dimulai 5 hari sebelum ovulasi.', null, 11),
('fertile', 'fact', 'Sel telur sekali kesempatan', 'Sel telur viable hanya 12 sampai 24 jam setelah dilepaskan. Sperma bisa menunggu, sel telur tidak.', null, 12),
('fertile', 'fact', 'Pitch suara naik tipis', 'Studi 2008 (Bryant): perempuan bersuara sedikit lebih tinggi di fertile window. Sinyal subliminal.', null, 13),
('fertile', 'fact', 'Penciuman lebih sensitif', 'Estrogen meningkatkan persepsi penciuman. Banyak laporan everything smells stronger di fertile.', null, 14),
('fertile', 'fact', 'Studi atraktivitas', 'Multiple studi (Roberts 2004, Haselton 2007): perempuan dinilai lebih atraktif di fertile oleh laki-laki yang tidak tahu fase siklus.', null, 15),
('fertile', 'fact', 'Risk-taking turun', 'Berlawanan dengan dugaan, risk-taking justru turun di fertile (Bröder 2003). Mode hati-hati subconscious aktif.', null, 16),
('fertile', 'fact', 'Kesadaran tubuh puncak', 'Kesadaran kinestetik lebih tinggi. Banyak yang merasakan in tune with body khusus di fertile.', null, 17),
('fertile', 'fact', 'Saliva ferning', 'Saliva yang dikeringkan di kaca lalu dilihat di mikroskop membentuk pola seperti pakis saat estrogen tinggi.', null, 18),
('fertile', 'fact', 'Tidur lebih dalam', 'BBT pre-ovulasi rendah dan serotonin seimbang membuat deep sleep lebih mudah dicapai.', null, 19),
('fertile', 'fact', 'Serviks lembut seperti bibir', 'Pre-fertile: kencang seperti hidung. Fertile: lembut seperti bibir. Tanda taktil signifikan.', null, 20),
('fertile', 'fact', 'Tes Spinnbarkeit', 'Tarik lendir antara 2 jari. Stretchy 5 sampai 10 cm tanpa putus menandakan puncak fertilitas.', null, 21),
('fertile', 'fact', 'Konsepsi paling probable', 'Walaupun jendela subur 6 hari, konsepsi paling probable di hari minus 1 dan hari 0 (ovulasi). Sperma dan sel telur sama-sama segar.', null, 22),
('fertile', 'fact', 'Energi masih tinggi', 'Estrogen tinggi membawa energi carry-over dari folikular. Olahraga dan proyek masih mengalir.', null, 23),
('fertile', 'fact', 'Pentingnya tracking', 'Walau tidak merencanakan konsepsi, tahu jendela subur memberi kontrol. Body literacy adalah dasar self-care.', null, 24),
('fertile', 'fact', 'Body temperature shift', 'Setelah ovulasi, BBT akan naik 0,3 sampai 0,5 derajat Celsius. Pengamatan retrospektif yang reliable.', null, 25),
('fertile', 'fact', 'Faktor sperma', 'Kualitas dan jumlah sperma juga memengaruhi konsepsi. Pasangan dengan kualitas sperma rendah perlu evaluasi medis.', null, 26),
('fertile', 'fact', 'Bayi kembar fraternal', 'Sekitar 1 dari 80 ovulasi melepaskan 2 telur, dasar bayi kembar fraternal jika keduanya dibuahi.', null, 27),
('fertile', 'fact', 'Cervix buka dan tutup', 'Pintu serviks (os) terbuka kecil di fertile, menutup setelah ovulasi. Adaptasi tubuh untuk memfasilitasi konsepsi.', null, 28),
('fertile', 'fact', 'Kompleks lendir', 'Lendir serviks fertile berfungsi sebagai filter: sperma sehat lolos, sperma abnormal terjebak.', null, 29),
('fertile', 'fact', 'Tubuh suhu naik dini', 'Beberapa perempuan merasakan tubuh sedikit lebih hangat di fertile, tanda sirkulasi yang aktif.', null, 30),

-- ===== Tip (25) =====
('fertile', 'tip', 'Cek lendir saat mandi', 'Bilas dengan tisu setelah BAB atau jari saat mandi. Lendir basah, licin, kenyal menandakan puncak.', null, 50),
('fertile', 'tip', 'BBT konsisten', 'Ukur saat bangun tidur sebelum bergerak, di jam yang sama. Pre-ovulasi steady, post-ovulasi jelas naik.', null, 51),
('fertile', 'tip', 'LH strip pagi dan sore', 'Lonjakan LH 24 sampai 36 jam. Tes 2 kali sehari untuk menangkap timing optimal jika merencanakan konsepsi.', null, 52),
('fertile', 'tip', 'Folat untuk konsepsi', 'Folat 400 mcg per hari, mulai 3 bulan sebelum konsepsi. Mengurangi risiko neural tube defect secara signifikan.', null, 53),
('fertile', 'tip', 'Kurangi alkohol', 'Alkohol memengaruhi kualitas sperma dan sel telur. Cut atau minimize selama jendela subur.', null, 54),
('fertile', 'tip', 'Hidrasi ekstra', 'Kualitas lendir serviks tergantung hidrasi. Air putih cukup mendukung lendir yang sperm-friendly.', null, 55),
('fertile', 'tip', 'Pelumas sperm-friendly', 'Sebagian besar lubricant bersifat spermicidal. Jika merencanakan konsepsi, gunakan Pre-Seed atau alami.', null, 56),
('fertile', 'tip', 'Pasangan hindari hot tub', 'Sperma ideal 1 sampai 2 derajat Celsius di bawah suhu tubuh. Hot tub berkala mengurangi kualitas sperma 3 bulan ke depan.', null, 57),
('fertile', 'tip', 'Kurangi kafein', 'Kafein berlebihan (lebih dari 300 mg per hari) berkaitan dengan delay konsepsi. Kurangi jika merencanakan kehamilan.', null, 58),
('fertile', 'tip', 'Perhatikan body cues', 'Perut sedikit kembung, payudara sensitif ringan. Tubuh memberikan sinyal, perhatikan.', null, 59),
('fertile', 'tip', 'Ovulation predictor kit', 'OPK mendeteksi lonjakan LH. Pee on stick, baca dalam 5 menit. Akurasi 95 persen jika kalibrasi tepat.', null, 60),
('fertile', 'tip', 'BMI sehat', 'BMI ekstrim (under atau over) dapat mengganggu ovulasi. Range sehat mendukung siklus reguler dan fertilitas lebih baik.', null, 61),
('fertile', 'tip', 'Berhenti merokok', 'Merokok mempercepat penuaan ovarium. Setiap pack-year menurunkan AMH (cadangan sel telur).', null, 62),
('fertile', 'tip', 'Tidur 7 sampai 9 jam', 'Kurang tidur dapat mengganggu timing lonjakan LH. Konsepsi lebih sulit jika kurang tidur kronis.', null, 63),
('fertile', 'tip', 'Manajemen stres', 'Kortisol tinggi dapat menunda ovulasi. Yoga, meditasi, atau jalan di alam yang menenangkan.', null, 64),
('fertile', 'tip', 'Frekuensi seksual', 'Untuk konsepsi: setiap 1 sampai 2 hari di jendela subur optimal. Setiap hari juga oke, jumlah sperma cepat pulih.', null, 65),
('fertile', 'tip', 'Mitos posisi', 'Tidak ada bukti ilmiah posisi memengaruhi probabilitas konsepsi. Apa pun yang nyaman.', null, 66),
('fertile', 'tip', 'Catat pola berbulan', 'Setiap fertile window berbeda halus. Tracking 3 bulan mengungkap pola personal Kamu.', null, 67),
('fertile', 'tip', 'Coenzyme Q10', 'Studi awal menunjukkan CoQ10 100 sampai 200 mg per hari dapat mendukung kualitas sel telur. Konsultasi dokter sebelum mulai.', null, 68),
('fertile', 'tip', 'Reduce inflamasi diet', 'Kurangi gula dan trans fat. Tambah omega-3 (salmon, flaxseed) untuk mendukung kualitas sel telur.', null, 69),
('fertile', 'tip', 'Akupuntur kalau planning', 'Akupuntur fertilitas didukung beberapa studi. Cocok sebagai pelengkap medis konvensional.', null, 70),
('fertile', 'tip', 'Folic acid versus folate', 'Folate (bentuk alami) lebih mudah diserap dibanding folic acid sintetis bagi sebagian perempuan. Cek label suplemen.', null, 71),
('fertile', 'tip', 'Vitamin D check', 'Vitamin D memengaruhi reseptor di ovarium. Cek kadar 25(OH)D, suplemen jika kurang dari 30 ng/ml.', null, 72),
('fertile', 'tip', 'Pemeriksaan kesehatan', 'Sebelum merencanakan konsepsi, pemeriksaan kesehatan menyeluruh: tiroid, gula darah, vitamin, vaksinasi.', null, 73),
('fertile', 'tip', 'Selangi olahraga intens', 'Latihan intens berlebihan dapat mengganggu ovulasi. Kombinasi kardio sedang dan latihan kekuatan optimal.', null, 74),

-- ===== Trivia (8) =====
('fertile', 'trivia', 'Asal istilah putih telur', 'Lendir serviks fertile sama struktur dengan putih telur: keduanya berbasis protein dan elastis. Bukan kebetulan.', null, 90),
('fertile', 'trivia', 'Sperma seperti maraton', 'Sperma 60 mikrometer, berenang 5 mm per menit di lendir. Setara manusia berenang 100 meter dalam 1 panjang badan.', null, 91),
('fertile', 'trivia', 'Fertility Awareness Method', 'FAM (metode kesadaran fertilitas) adalah natural family planning dengan tracking BBT, lendir, dan kalender. Failure rate 0,4 sampai 5 persen.', null, 92),
('fertile', 'trivia', 'Catholic Rhythm Method', 'Vatikan menerima Knaus-Ogino sebagai metode kontrasepsi natural sah pada tahun 1951. Dasar metode kalender modern.', null, 93),
('fertile', 'trivia', 'Sperma pertama dideteksi', 'Anton van Leeuwenhoek pertama melihat sperma dengan mikroskop pada tahun 1677. Awalnya disebut animalcules.', null, 94),
('fertile', 'trivia', 'Telur paling besar', 'Sel telur manusia paling besar di tubuh (0,1 mm) dan visible dengan mata telanjang. Sperma berukuran 60 mikrometer, harus mikroskop.', null, 95),
('fertile', 'trivia', 'Identical twins berbeda mekanisme', 'Identical twins (1 telur split) tidak terkait dengan ovulasi multiple. Kejadian random sekitar 1 dari 250 kelahiran.', null, 96),
('fertile', 'trivia', 'Dr. Marie Stopes pelopor', 'Dr. Marie Stopes menulis Married Love (1918) dan menjadi pelopor edukasi kesehatan reproduksi modern.', null, 97),

-- ===== Lifestyle (12) =====
('fertile', 'lifestyle', 'Outfit percaya diri', 'Kepercayaan diri puncak. Pakai outfit yang biasa Kamu ragukan, feedback loop positif terjadi.', null, 110),
('fertile', 'lifestyle', 'Highlight skincare', 'Kulit bercahaya alami. Saat investasi di treatment yang biasa terlewat, seperti masker atau eye cream.', null, 111),
('fertile', 'lifestyle', 'Playlist sensual', 'Slow R&B, romantic ballads, jazz. Mood selaras.', null, 112),
('fertile', 'lifestyle', 'Sensory awareness', 'Makan perlahan, savor textures. Indra lebih tajam, manfaatkan untuk menikmati kesenangan kecil.', null, 113),
('fertile', 'lifestyle', 'Plan date special', 'Pasangan: rencana spesial. Solo: rencana spesial dengan diri sendiri. Fase ini layak dirayakan.', null, 114),
('fertile', 'lifestyle', 'Mood photography', 'Cahaya dan glow di fase ini sering paling fotogenik. Self-timer plus mirror untuk dokumentasi confidence.', null, 115),
('fertile', 'lifestyle', 'Jalan di alam', 'Indra heightened amplify pengalaman. Bunga, suara angin lebih nyata. Jalan 30 menit di taman atau hutan.', null, 116),
('fertile', 'lifestyle', 'Cook with intention', 'Slow cooking, intentional meal prep. Solo atau bersama pasangan, makanan jadi ritual.', null, 117),
('fertile', 'lifestyle', 'Baca puisi', 'Bandwidth emosional terbuka. Puisi terasa lebih dalam. Coba Rumi, Mary Oliver, atau Sapardi Djoko Damono.', null, 118),
('fertile', 'lifestyle', 'Ekspresikan secara kreatif', 'Lukis, tulis, menari, channel energi ke seni. Fisik atau digital, tidak masalah.', null, 119),
('fertile', 'lifestyle', 'Coba parfum baru', 'Penciuman lebih sensitif. Coba sample parfum di toko, mungkin temukan favorit baru.', null, 120),
('fertile', 'lifestyle', 'Wine tasting', 'Apresiasi rasa puncak. Wine atau teh tasting di rumah dengan beberapa varian, lebih menyenangkan dari biasanya.', null, 121);

-- ============ OVULATION (75 entries) ============
insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values

-- ===== Fact (30) =====
('ovulation', 'fact', 'Hari ini puncak fertilitas', 'Sel telur dilepaskan 24 jam lalu atau hari ini. Jendela konsepsi paling tinggi.', null, 1),
('ovulation', 'fact', 'Lonjakan LH memicu', 'Lonjakan LH 24 sampai 36 jam lalu memicu follicle dominan pecah dan melepas sel telur. Proses berlangsung beberapa menit.', null, 2),
('ovulation', 'fact', 'Sel telur viable 12 sampai 24 jam', 'Setelah keluar dari ovarium, sel telur viable hanya sehari. Itulah sebabnya jendela fertilitas ketat.', null, 3),
('ovulation', 'fact', 'Estrogen drop tajam', 'Setelah puncak kemarin, estrogen turun sekitar 50 persen dalam 24 jam. Dapat menyebabkan mood shift halus.', null, 4),
('ovulation', 'fact', 'Progesteron mulai produksi', 'Corpus luteum (sisa follicle) mulai memproduksi progesteron. Ini akan dominan 14 hari ke depan.', null, 5),
('ovulation', 'fact', 'BBT akan naik', 'Progesteron menaikkan BBT 0,3 sampai 0,5 derajat Celsius. Cek besok pagi, BBT lebih tinggi sebagai konfirmasi ovulasi.', null, 6),
('ovulation', 'fact', 'Mittelschmerz hari ini', '15 sampai 20 persen merasakan twinge tajam di sisi ovarium yang berovulasi. Mittel berarti tengah, schmerz berarti nyeri.', null, 7),
('ovulation', 'fact', 'Lendir serviks puncak', 'Hari ini lendir mencapai puncak (paling kenyal). Besok mulai mengering sebagai tanda ovulasi telah lewat.', null, 8),
('ovulation', 'fact', 'Serviks paling terbuka', 'Serviks paling tinggi, paling lunak, paling terbuka. Besok mulai turun dan menutup.', null, 9),
('ovulation', 'fact', 'Libido puncak biologis', 'Cocktail hormonal memberikan attraction dan responsiveness maksimum. Tubuh dirancang untuk reproduksi prime time.', null, 10),
('ovulation', 'fact', 'Studi simetri tubuh', 'Studi: deteksi simetri wajah lebih akurat di ovulasi. Penilaian kualitas pasangan secara subconscious meningkat.', null, 11),
('ovulation', 'fact', 'Preferensi penciuman', 'Studi 2003: perempuan lebih menyukai aroma pasangan dengan profil MHC maskulin saat ovulasi. Subtle tapi terukur.', null, 12),
('ovulation', 'fact', 'Pitch suara naik halus', 'Pitch suara sedikit naik saat ovulasi (Pipitone 2008). Sinyal mate-attraction lintas budaya.', null, 13),
('ovulation', 'fact', 'Risk-taking kompleks', 'Counter-intuitively, risk-taking lebih konservatif di ovulasi (Bröder 2003). Mode protektif tubuh aktif.', null, 14),
('ovulation', 'fact', 'Probabilitas kembar naik', 'Hari ini, kemungkinan ovulate 2 sel telur (kembar fraternal jika keduanya dibuahi) maksimum dibanding hari lain.', null, 15),
('ovulation', 'fact', 'Glow kulit puncak puncak', 'Estrogen puncak kemarin plus sirkulasi puncak hari ini, banyak yang merasakan kulit lit from within.', null, 16),
('ovulation', 'fact', 'Energi puncak ganda', 'Hari terakhir mood high-energy folikular. Besok tubuh shift gear ke recovery mode luteal.', null, 17),
('ovulation', 'fact', 'Kognitif spasial', 'Spatial reasoning sedikit menurun saat estrogen puncak (Hampson 1990). Kemampuan verbal masih tajam.', null, 18),
('ovulation', 'fact', 'Perjalanan sel telur', 'Sel telur dilepas ke fimbriae fallopian tube, menyapu menuju rahim selama 6 sampai 12 hari. Konsepsi terjadi di tube.', null, 19),
('ovulation', 'fact', 'Progesteron menghangatkan', 'Progesteron bersifat thermogenic. Bisa terasa lebih hangat atau berkeringat ringan saat tidur.', null, 20),
('ovulation', 'fact', 'Mitos midcycle ovulation', 'Hanya akurat untuk siklus 28 hari. Real ovulasi: cycle_length minus 14 hari dari haid berikutnya.', null, 21),
('ovulation', 'fact', 'PCOS dan ovulasi', 'Polycystic Ovary Syndrome (PCOS) sering anovulatory atau ovulasi tidak teratur. Tracking tetap berguna untuk diagnosis.', null, 22),
('ovulation', 'fact', 'Satu sel telur per siklus', '99 persen siklus melepas 1 sel telur. Kedua ovarium bergantian, tidak strictly. Tubuh menentukan berdasarkan maturasi follicle.', null, 23),
('ovulation', 'fact', 'Besok ovulasi terlewat', 'Tanda tubuh berbalik: BBT naik, lendir kering, serviks menutup. Verifikasi semua retrospektif. Tracking untuk membentuk pola.', null, 24),
('ovulation', 'fact', 'Daya prediktif OPK', 'Ovulation Predictor Kit (OPK) akurat untuk timing konsepsi. Lebih reliable dari sekedar perhitungan kalender.', null, 25),
('ovulation', 'fact', 'Sperma matchmaking', 'Sel telur menarik sperma melalui chemoattractants. Sperma yang paling sehat lebih mudah menuju sel telur.', null, 26),
('ovulation', 'fact', 'Telur dilengkapi nutrisi', 'Sel telur sangat besar karena membawa nutrisi awal embrio. Sperma kontribusi DNA, sel telur kontribusi nutrisi.', null, 27),
('ovulation', 'fact', 'Pelepasan dari folikel', 'Saat ovulasi, follicle pecah dan sel telur dilepas. Cairan folikular juga ikut terbuang ke kavum peritoneal.', null, 28),
('ovulation', 'fact', 'Pearl Index Knaus-Ogino', 'Method kalender Knaus-Ogino punya Pearl Index 9 sampai 25 (typical use). Lebih efektif jika dikombinasi tracking lain.', null, 29),
('ovulation', 'fact', 'Lonjakan estradiol', 'Estradiol puncak 250 sampai 400 pg/ml saat ovulasi, hampir 10 kali lipat fase folikular awal.', null, 30),

-- ===== Tip (25) =====
('ovulation', 'tip', 'Cek BBT besok pagi', 'Malam ini malam terakhir suhu rendah. Besok pagi suhu naik adalah konfirmasi retrospektif ovulasi hari ini.', null, 50),
('ovulation', 'tip', 'Hidrasi ekstra', 'Drop estrogen menyebabkan dehidrasi halus. Air putih cukup membantu tubuh tetap stabil.', null, 51),
('ovulation', 'tip', 'Catat sensasi tubuh', 'Mittelschmerz, breast tender, libido. Catat semua. Pengenalan pola siklus ke siklus adalah skill.', null, 52),
('ovulation', 'tip', 'Magnesium proaktif', 'Mulai suplementasi Mg 200 sampai 300 mg per hari. Membantu transisi ke luteal lebih halus.', null, 53),
('ovulation', 'tip', 'Hari latihan keras terakhir', 'Tubuh masih anabolic-friendly. Latihan kekuatan besok masih oke, tapi capitalize hari ini.', null, 54),
('ovulation', 'tip', 'Romantisme date night', 'Libido puncak dan keterbukaan emosional cocok untuk merencanakan evening spesial dengan pasangan.', null, 55),
('ovulation', 'tip', 'Mode pengambilan keputusan', 'Klaritas dan kecerdasan emosional baik. Keputusan sulit yang Kamu tunda? Hadapi hari ini.', null, 56),
('ovulation', 'tip', 'Kontrasepsi backup', 'Hari ovulasi adalah resiko kehamilan tertinggi (jika ada hubungan tanpa proteksi). Double up barrier method.', null, 57),
('ovulation', 'tip', 'Konsumsi omega-3', 'Salmon, walnut, chia seeds. Omega-3 anti-inflamasi membantu tubuh transisi ke luteal lebih halus.', null, 58),
('ovulation', 'tip', 'Prioritaskan tidur', 'Tidur berkualitas malam ini adalah dasar pemulihan untuk luteal. Hindari kafein setelah jam 14:00.', null, 59),
('ovulation', 'tip', 'Makan malam ringan', 'Makan berat malam ini berarti pencernaan bersaing dengan recovery tubuh. Pilih makanan ringan dan padat nutrisi.', null, 60),
('ovulation', 'tip', 'Refleksi energi', 'Bagaimana tubuh terasa hari ini? Energi 1 sampai 10? Catat. Bandingkan siklus berikutnya untuk pola.', null, 61),
('ovulation', 'tip', 'Ritual menenangkan', 'Besok mulai luteal. Tubuh shift ke mode lebih lambat. Ease in malam ini: teh, mandi hangat, jurnal.', null, 62),
('ovulation', 'tip', 'Antisipasi luteal', 'Lihat kalender 14 hari ke depan. Jadwalkan tugas berat sebelum PMS, tugas ringan setelahnya. Plan with self.', null, 63),
('ovulation', 'tip', 'Apresiasi diri', 'Tulis 3 hal yang Kamu syukuri tentang tubuh hari ini. Self-acknowledgment yang konkret.', null, 64),
('ovulation', 'tip', 'Check-in dengan pasangan', 'Jika pasangan supporter aware fase ovulasi, hari ini quality time. Komunikasi puncak.', null, 65),
('ovulation', 'tip', 'Capture mood', 'Foto, jurnal, voice note untuk dokumentasi vibe hari ini. Referensi saat luteal terasa down.', null, 66),
('ovulation', 'tip', 'Pilih makanan manis sehat', 'Mulai craving manis? Dark chocolate 70 persen, buah, atau madu. Kualitas lebih dari kuantitas.', null, 67),
('ovulation', 'tip', 'Suplemen vitamin C', '500 sampai 1000 mg vitamin C mendukung sintesis hormon. Sumber alami: jeruk, paprika merah, brokoli.', null, 68),
('ovulation', 'tip', 'Pilih posisi tidur', 'Tidur miring kiri membantu sirkulasi optimal. Posisi penting untuk recovery semalam.', null, 69),
('ovulation', 'tip', 'Kurangi gula', 'Drop estrogen plus craving manis bisa memicu spike gula. Pilih protein dan serat untuk stabil.', null, 70),
('ovulation', 'tip', 'Rencana minggu depan', 'Klaritas mental masih ada. Rencanakan 1 minggu ke depan dengan realistis sebelum mood luteal mengubah persepsi.', null, 71),
('ovulation', 'tip', 'Photography golden hour', 'Cahaya golden hour sore selaras dengan glow tubuh hari ini. Self-timer di outdoor untuk dokumentasi.', null, 72),
('ovulation', 'tip', 'Asah ekspresi seni', 'Channel energi creative ke karya. Mulai painting, writing, atau crafting yang sudah lama tertunda.', null, 73),
('ovulation', 'tip', 'Perawatan tubuh', 'Body scrub, mask wajah, perawatan kuku. Pampering session di puncak glow tubuh.', null, 74),

-- ===== Trivia (8) =====
('ovulation', 'trivia', 'OPK home test diperkenalkan', 'OPK home test dipopulerkan tahun 1980-an. Sebelumnya hanya BBT chart yang tedious dan retrospektif.', null, 90),
('ovulation', 'trivia', 'Kata mittelschmerz', 'Diciptakan oleh dokter Jerman tahun 1840-an. Translasi literal: nyeri tengah. Bahasa yang presisi.', null, 91),
('ovulation', 'trivia', 'Lifespan corpus luteum', 'Corpus luteum berumur 12 sampai 16 hari jika tidak ada konsepsi. Programmed cell death sebagai jam biologis.', null, 92),
('ovulation', 'trivia', 'Kembar fraternal probabilitas', 'Spontaneous fraternal twins: 1 dalam 80 ovulasi. Kembar identik (telur sama yang split): 1 dalam 250, independen ras.', null, 93),
('ovulation', 'trivia', 'Ukuran ovum dan sperma', 'Sel telur 0,1 mm (mata telanjang melihat). Sperma 60 mikrometer (perlu mikroskop). Sel telur 1000x lebih besar.', null, 94),
('ovulation', 'trivia', 'Reinier de Graaf', 'Dokter Belanda yang pertama mendeskripsikan follicle ovarium tahun 1672. Sekarang disebut Graafian follicle.', null, 95),
('ovulation', 'trivia', 'Pearl Index method natural', 'Method natural family planning modern (sympto-thermal) memiliki Pearl Index 0,4 perfect use, 5 typical use. Setara pil hormonal.', null, 96),
('ovulation', 'trivia', 'Bayi tabung pertama', 'Louise Brown lahir tahun 1978 sebagai bayi tabung pertama. IVF memberi alternatif bagi pasangan dengan masalah fertilitas.', null, 97),

-- ===== Lifestyle (12) =====
('ovulation', 'lifestyle', 'Outfit spesial', 'Glow dan confidence puncak. Pakai sesuatu yang terasa celebratory.', null, 110),
('ovulation', 'lifestyle', 'Skincare lembut', 'Hari ini tidak perlu agresif. Kulit sudah di puncak. Gentle cleanse dan moisturize.', null, 111),
('ovulation', 'lifestyle', 'Playlist passion', 'Lagu-lagu yang membangkitkan sesuatu. Genre apa pun yang sesuai mood Kamu hari ini.', null, 112),
('ovulation', 'lifestyle', 'Connect dengan alam', 'Sunset walk, taman, pantai jika memungkinkan. Indra heightened memperdalam pengalaman.', null, 113),
('ovulation', 'lifestyle', 'Cook with love', 'Slow cooking, intentional meal prep. Solo atau bersama pasangan, makanan jadi ritual.', null, 114),
('ovulation', 'lifestyle', 'Photography candid', 'Self-portrait atau dengan pasangan. Cahaya hari ini sering paling flattering.', null, 115),
('ovulation', 'lifestyle', 'Baca puisi', 'Bandwidth emosional terbuka. Puisi terasa lebih dalam.', null, 116),
('ovulation', 'lifestyle', 'Ekspresikan kreatif', 'Paint, write, dance, channel energi ke seni.', null, 117),
('ovulation', 'lifestyle', 'Aroma terapi', 'Diffuser dengan rose, jasmine, atau ylang-ylang melengkapi mood ovulasi.', null, 118),
('ovulation', 'lifestyle', 'Spa di rumah', 'Mask wajah, hair treatment, scrub badan. Rangkaian self-care 1 jam.', null, 119),
('ovulation', 'lifestyle', 'Decluttering kreatif', 'Organize lemari pakaian dengan tema. Visualisasi naik, kreativitas mendukung.', null, 120),
('ovulation', 'lifestyle', 'Belajar makeup baru', 'Eksperimen lipstik bold atau eyeshadow shade baru. Confidence puncak mendukung percobaan.', null, 121);

-- ============ LUTEAL (75 entries) ============
insert into public.daily_insights (phase, category, title_id, body_id, emoji, display_order) values

-- ===== Fact (30) =====
('luteal', 'fact', 'Fase luteal dimulai', 'Setelah ovulasi, tubuh masuk fase luteal sekitar 14 hari. Progesteron naik memberikan vibe berbeda dari folikular.', null, 1),
('luteal', 'fact', 'Progesteron dominan', 'Hormon utama luteal. Stabilkan endometrium jika konsepsi terjadi. Jika tidak, drop memicu haid.', null, 2),
('luteal', 'fact', 'BBT tetap tinggi', 'BBT tetap tinggi sampai akhir luteal. Drop tajam menjadi sinyal haid besoknya.', null, 3),
('luteal', 'fact', 'PMS akhir luteal', 'Premenstrual Syndrome biasanya muncul 7 sampai 10 hari sebelum haid. Pergeseran hormonal jadi penyebab biologis.', null, 4),
('luteal', 'fact', 'Energi menurun bertahap', 'Berbeda dari folikular high-energy, luteal pace lebih lambat. Tubuh bergeser fokus ke persiapan recovery.', null, 5),
('luteal', 'fact', 'Cravings dijelaskan', 'Drop progesteron plus serotonin memicu craving karbohidrat manis. Tubuh mencari prekursor serotonin.', null, 6),
('luteal', 'fact', 'Bloating fisiologis', 'Progesteron memperlambat motilitas usus, menyebabkan konstipasi dan bloat. Plus retensi air. Keduanya sementara.', null, 7),
('luteal', 'fact', 'Payudara sensitif umum', 'Progesteron memicu proliferasi duktal di payudara. Kembali normal saat haid mulai.', null, 8),
('luteal', 'fact', 'Mood lability', 'Pergeseran hormonal memengaruhi neurotransmitter. Mood swing valid secara biologis, bukan emosi yang dilebih-lebihkan.', null, 9),
('luteal', 'fact', 'Tidur sering terganggu', 'BBT tinggi mengganggu arsitektur tidur. Bangun lebih sering, tidur lebih ringan.', null, 10),
('luteal', 'fact', 'Jerawat hormonal', 'Progesteron dan androgen rebalance meningkatkan produksi sebum. Jerawat akhir luteal umum.', null, 11),
('luteal', 'fact', 'Spike kecemasan', 'Sistem GABA dipengaruhi metabolit progesteron. Sebagian merasakan kecemasan naik khusus di luteal.', null, 12),
('luteal', 'fact', 'Sakit kepala hormonal', 'Drop estrogen akhir luteal memicu menstrual migraine. Bedakan dengan tension headache.', null, 13),
('luteal', 'fact', 'Sensitivitas insulin turun', 'Tubuh kurang efisien memproses karbo dibanding folikular. Steady protein dan serat lebih ideal.', null, 14),
('luteal', 'fact', 'Kortisol elevated', 'Respons stres heightened di luteal. Trigger yang sama terasa more stressful dibanding folikular.', null, 15),
('luteal', 'fact', 'PMDD bentuk parah', 'Premenstrual Dysphoric Disorder adalah PMS parah yang mengganggu fungsi harian. 3 sampai 8 persen perempuan menstruasi. Diakui DSM-5.', null, 16),
('luteal', 'fact', 'Memori shift halus', 'Recall sedikit lebih lambat dibanding folikular. Memori jangka pendek tidak terpengaruh. Variabel per individu.', null, 17),
('luteal', 'fact', 'Ambang nyeri turun', 'Drop estrogen menyebabkan nyeri terasa lebih intens. Same level kram bisa dirasakan berbeda di scale.', null, 18),
('luteal', 'fact', 'Libido turun bertahap', 'Berlawanan dengan folikular. Sebagian merasakan drop tajam, lainnya bertahap. Keduanya normal.', null, 19),
('luteal', 'fact', 'Suhu tubuh lebih hangat', 'Sering perlu kamar tidur lebih dingin. Layered bedding memudahkan adjusting suhu.', null, 20),
('luteal', 'fact', 'Tanda haid mendekat', '4 sampai 5 hari pre-haid: spotting ringan, lendir coklat atau krem, payudara sensitif puncak. Tubuh menyelesaikan siklus.', null, 21),
('luteal', 'fact', 'Serviks turun dan menutup', 'Serviks turun, mengeras, menutup di luteal. Berbalik dari fase ovulasi.', null, 22),
('luteal', 'fact', 'Asal kata luteal', 'Dari corpus luteum (yellow body), sisa follicle yang memproduksi progesteron.', null, 23),
('luteal', 'fact', 'Treatment PMDD', 'SSRI (antidepressant), kontrasepsi hormonal, atau intervensi lifestyle. Konsultasikan profesional kesehatan.', null, 24),
('luteal', 'fact', 'PMS bukan total negatif', 'Hingga 75 persen mengalami gejala PMS, biasanya ringan. Severe (PMDD) hanya subset kecil. Tanpa stigma.', null, 25),
('luteal', 'fact', 'Tahap sekretori', 'Endometrium memasuki tahap sekretori: kelenjar membesar, mengeluarkan glikogen sebagai persiapan implantasi.', null, 26),
('luteal', 'fact', 'Hot flash mini', 'Sebagian merasakan hot flash mini di luteal akibat fluktuasi hormonal. Mirip pra-menopause tetapi sementara.', null, 27),
('luteal', 'fact', 'Nausea mungkin', 'Sebagian merasakan mual ringan akhir luteal. Terkait progesteron tinggi yang juga dialami di kehamilan awal.', null, 28),
('luteal', 'fact', 'Pertumbuhan rambut wajah', 'Androgen relatif lebih tinggi vs estrogen di akhir luteal. Bisa muncul jerawat atau rambut wajah halus.', null, 29),
('luteal', 'fact', 'Migrain pre-haid', 'Sekitar 60 persen perempuan dengan migrain mengalami episode pre-haid. Disebut menstrual migraine.', null, 30),

-- ===== Tip (25) =====
('luteal', 'tip', 'Olahraga lebih ringan', 'Cardio LISS atau yoga lebih dari HIIT. Tubuh lebih efisien di steady-state phase ini.', null, 50),
('luteal', 'tip', 'Magnesium untuk PMS', '300 sampai 400 mg per hari. Membantu mood, kram, dan tidur. Bentuk glycinate gentle untuk lambung.', null, 51),
('luteal', 'tip', 'Vitamin B6', 'Hingga 100 mg per hari membantu PMS mood. Konsultasikan dokter untuk konsumsi jangka panjang.', null, 52),
('luteal', 'tip', 'Kurangi garam', 'Sodium tinggi memperparah retensi air dan bloat. Kurangi makanan olahan asin.', null, 53),
('luteal', 'tip', 'Tingkatkan serat', 'Serat untuk motilitas. 25 sampai 30 g per hari mencegah konstipasi luteal. Apel, oat, lentil.', null, 54),
('luteal', 'tip', 'Seed cycling', 'Konsumsi flax dan pumpkin seeds di paruh luteal. Anekdotal practice, sebagian melaporkan perbaikan subjektif.', null, 55),
('luteal', 'tip', 'Restorative yoga', 'Forward folds, child pose, supine twist. Menenangkan sistem saraf simpatik.', null, 56),
('luteal', 'tip', 'Prioritas tidur ekstra', 'Tubuh terganggu ekstra. Tidur lebih awal, kamar gelap, jadwal konsisten.', null, 57),
('luteal', 'tip', 'Hidrasi dengan elektrolit', 'Air biasa kadang tidak cukup. Air kelapa atau pinch garam plus lemon membantu.', null, 58),
('luteal', 'tip', 'Batas kafein', 'Kafein memperparah cemas dan mengganggu tidur. Cap 200 mg per hari di paruh luteal.', null, 59),
('luteal', 'tip', 'Atur jadwal cermat', 'Presentasi besar? Jadwalkan lebih awal di luteal (pre-PMS). Simpan luteal akhir untuk tugas low cognitive.', null, 60),
('luteal', 'tip', 'Comfort food intentional', 'Craving karbo? Pilih karbohidrat kompleks (oat, quinoa, ubi). Energi sustained lebih dari spike gula.', null, 61),
('luteal', 'tip', 'Turunkan ekspektasi', 'Tidak apa jika kurang produktif di luteal akhir. Sesuaikan ekspektasi dengan kapasitas fase ini.', null, 62),
('luteal', 'tip', 'Boundaries firm', 'Tidak diperbolehkan jika kapasitas tidak ada. Saying yes saat low capacity hanya menumbuhkan resentment.', null, 63),
('luteal', 'tip', 'Self-care non-negotiable', 'Mandi hangat, jurnal, gentle yoga. Tandai kalender, luteal self-care adalah janji dengan diri.', null, 64),
('luteal', 'tip', 'Paparan sinar matahari', '10 sampai 15 menit sinar pagi membantu mood dan ritme tidur. Sangat membantu di luteal akhir.', null, 65),
('luteal', 'tip', 'Batasi berita dan media sosial', 'Konten kortisol-amplifying dihindari di luteal akhir. Konsumsi media sosial dan berita secara mindful.', null, 66),
('luteal', 'tip', 'Hubungi orang aman', 'Bicara dengan teman atau keluarga yang Kamu percayai. Koneksi mengimbangi keberatan luteal.', null, 67),
('luteal', 'tip', 'Konsumsi triptofan', 'Pisang, kalkun, telur, kacang. Triptofan adalah prekursor serotonin yang sering kurang di luteal.', null, 68),
('luteal', 'tip', 'Latihan napas dalam', 'Breathing exercise 4-7-8 (inhale 4s, hold 7s, exhale 8s) mengaktifkan parasimpatik. Lakukan 4 siklus saat cemas.', null, 69),
('luteal', 'tip', 'Cuci muka 2 kali sehari', 'Sebum naik di akhir luteal. Cleanse pagi dan malam, hindari over-washing yang justru memicu lebih banyak minyak.', null, 70),
('luteal', 'tip', 'Konsumsi kalsium', '1200 mg kalsium per hari (dari makanan dan suplemen) dapat mengurangi keparahan PMS sesuai studi 2017.', null, 71),
('luteal', 'tip', 'Pijat perut bawah', 'Pijat perut searah jarum jam dengan minyak hangat 5 sampai 10 menit membantu meredakan tegangan.', null, 72),
('luteal', 'tip', 'Refleksi mingguan', 'Sebelum mood luteal puncak, refleksikan minggu lalu. Kapasitas mental masih cukup untuk evaluasi jujur.', null, 73),
('luteal', 'tip', 'Hindari keputusan besar', 'Jika memungkinkan, tunda keputusan major (pindah kerja, putus hubungan) sampai post-haid. Klaritas akan membaik.', null, 74),

-- ===== Trivia (8) =====
('luteal', 'trivia', '14-day luteal default', 'ACOG: fase luteal 12 sampai 16 hari. Jika cycle 28, ovulasi hari 14. Cycle 35, ovulasi hari 21.', null, 90),
('luteal', 'trivia', 'PMS coined 1953', 'Istilah Premenstrual Tension oleh Greene dan Dalton tahun 1953. PMS resmi DSM tahun 1994 (PMDD).', null, 91),
('luteal', 'trivia', 'Mengapa craving asin', 'Aldosterone fluktuasi di luteal mengubah water balance. Tubuh mencari asin sebagai kompensasi.', null, 92),
('luteal', 'trivia', 'Coklat kenapa craving', 'Dark chocolate memiliki magnesium, prekursor serotonin, dan anti-inflamasi. Tubuh secara intuitif tahu.', null, 93),
('luteal', 'trivia', 'PMS pada hewan', 'Beberapa hewan menunjukkan perubahan perilaku pre-haid, seperti primata, anjing in heat. Hormon lintas spesies.', null, 94),
('luteal', 'trivia', 'Penemu corpus luteum', 'Marcello Malpighi mendeskripsikan corpus luteum tahun 1697. Diberi nama yellow body karena warnanya kuning.', null, 95),
('luteal', 'trivia', 'PMS pertama dikatalogkan', 'Robert Frank tahun 1931 pertama mempublikasi paper ilmiah tentang premenstrual symptom. Disebut sebagai premenstrual tension.', null, 96),
('luteal', 'trivia', 'Korelasi PMS dan musim', 'Studi menunjukkan PMS lebih parah di musim dingin akibat kurang vitamin D dari sinar matahari.', null, 97),

-- ===== Lifestyle (12) =====
('luteal', 'lifestyle', 'Pakaian nyaman', 'Loose, layered, tidak ketat. Hindari restrictive waistbands. Tubuh nyaman, pikiran nyaman.', null, 110),
('luteal', 'lifestyle', 'Skincare disederhanakan', 'Jerawat breakout umum. Stick ke basics, jangan over-treat. Sabar.', null, 111),
('luteal', 'lifestyle', 'Playlist menenangkan', 'Lo-fi, ambient, soft folk. Sesuai mood fase ini.', null, 112),
('luteal', 'lifestyle', 'Buku genre lembut', 'Cozy mystery, slow memoir, self-help digestible. Simpan literatur berat untuk fase lebih tajam.', null, 113),
('luteal', 'lifestyle', 'Ritual mandi', 'Garam Epsom (magnesium), minyak lavender, air hangat. 20 menit detox dan relaksasi.', null, 114),
('luteal', 'lifestyle', 'Ritual teh malam', 'Chamomile, peppermint, jahe. Cangkir hangat plus buku plus tidur lebih awal sama dengan luteal evening sempurna.', null, 115),
('luteal', 'lifestyle', 'Pagi lebih lambat', 'Hindari alarm-rush. 5 menit stretching, kopi pelan, intentional start.', null, 116),
('luteal', 'lifestyle', 'Jurnal perasaan', 'Tuliskan apa yang muncul. Externalizing emosi adalah pelepasan. Tidak perlu struktur.', null, 117),
('luteal', 'lifestyle', 'Batasi acara sosial', 'Tandai kalender, luteal akhir berarti tanpa social commitment jika memungkinkan. Kualitas lebih dari kuantitas.', null, 118),
('luteal', 'lifestyle', 'Plant care therapy', 'Siram tanaman, prune, ngobrol dengan mereka. Ritual tenang yang grounding.', null, 119),
('luteal', 'lifestyle', 'Movie night cozy', 'Pilih film comfort, popcorn, blanket. Indoor entertainment cocok dengan low-energy phase.', null, 120),
('luteal', 'lifestyle', 'Cleanse mental', 'Unfollow akun media sosial yang membuat cemas. Mental decluttering di awal luteal mempersiapkan akhir luteal.', null, 121);
